import type { TranslationSet } from './types';
export const ar: TranslationSet = {
  nav: { home: 'الرئيسية', problem: 'المشكلة', hardware: 'الأجهزة', intelligence: 'الذكاء', operation: 'العمليات', security: 'الأمان', join: 'انضم إلينا!', mobileToggle: 'القائمة المحمولة', mobileNav: 'التنقل المحمول', mainNav: 'التنقل الرئيسي' },
  hero: { subtitle: 'في مواجهة أزمة المياه والغذاء العالمية، نبني نظامًا زراعيًا مستقلًا بالكامل قائمًا على RAG.', exploreBtn: 'اكتشف رؤيتنا', pitchBtn: 'تحميل Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'أزمة عالمية', title: 'نعرف المشكلة. ونبني الحل.', desc: 'لإطعام <strong>10 مليارات شخص بحلول 2050</strong>، يجب زيادة الإنتاج بنسبة 60%.', card1Title: 'كارثة صامتة: هدر المياه', card1Desc: '<strong>70%</strong> من المياه العذبة تُستخدم في الزراعة.', card2Title: 'الهشاشة المناخية', card2Desc: 'الزراعة التقليدية تحت رحمة الطبيعة.', card3Title: 'عزل البيانات', card3Desc: 'البيانات الزراعية تظل محلية ومعزولة.' },
  coreVision: { tag: 'تصميم النظام البيئي', title: 'محاكاة مناخية مثالية\nلكل نبتة، في كل مكان.', desc: 'نظام يقرأ البيانات و<strong>يغير البيئة</strong>.', feat1Title: 'التكيف الديناميكي', feat1Desc: 'يقرأ النظام الاحتياجات الأيضية الفورية.', feat2Title: 'شبكة التكملة الدقيقة', feat2Desc: 'يوفر <strong>المغذيات والمياه والحرارة والأسمدة</strong> بدقة.', feat3Title: 'محرك القرار المستقل', feat3Desc: '<strong>يُفعّل تلقائيًا</strong> تدخلات دقيقة.' },
  hardware: { watermark: 'الأجهزة', tag: 'بحث وتطوير', title: 'ذكاء مدمج في الحقل: sensSeries', desc: 'نصمم عائلة الأجهزة لنظام NaT البيئي.', sensTreeDesc: 'جهاز IoT على الجذع.', sensSoilDesc: 'مستشعر تحت الأرض.', sensPlantDesc: 'جهاز تتبع بمشبك للشتلات.' },
  rag: { watermark: 'الذكاء', tag: 'ذكاء اصطناعي RAG', title: 'خبرة عالمية، إجراء محلي.', desc: 'بنية RAG تجمع بين نماذج اللغة وقواعد البيانات الزراعية.', pred1Title: 'التنبؤ الاستباقي', pred1Desc: 'NaT يتنبأ: "خطر المرض 84% خلال 3 أيام."', pred2Title: 'التعلم الموحد الجماعي', pred2Desc: 'كل جهاز يدرب النموذج المركزي مع الحفاظ على الخصوصية.' },
  operation: { watermark: 'العمليات', tag: 'الرؤية التشغيلية', title: 'انتقال مستقل من التشخيص إلى العلاج', desc: 'هدفنا: تحويل البيانات إلى إجراء فيزيائي مستقل.', card1Title: 'تكامل API', card1Desc: 'الذكاء يرسل أوامر <strong>تدخل مستهدف</strong> للطائرات المسيرة.', card2Title: 'أقصى إنتاج', card2Desc: 'تقليل الكيماويات <strong>حتى 85%</strong>.' },
  lab: { title: 'في 4 خطوات', subtitle: 'نتفوق على اختبارات المختبر.', box1Title: 'ضياع الوقت', box1Desc: 'العينات والنتائج تستغرق أيامًا.', box2Title: 'خطأ العينات', box2Desc: 'حفنة من التراب تمثل حقلاً كاملاً.', box3Title: 'الانفصال عن النظام', box3Desc: 'لحظة استخراج العينة تبدأ البنية بالتحلل.', box4Title: 'بيانات ثابتة مقابل تدفق ديناميكي', box4Desc: 'اختبارات المختبر لقطة ثابتة فقط.' },
  security: { watermark: 'الأمان', tag: 'الدرع السيبراني', title: 'بيانات غير قابلة للتغيير،', title2: 'أجهزة لا يمكن الوصول إليها.', desc: 'بياناتك <strong>مشفرة من طرف إلى طرف</strong>.', card1Title: 'بروتوكول Match-Lock', card1Desc: 'الجهاز <strong>يقترن تشفيريًا</strong>.', card1Badge: 'الوضع الخفي', card2Title: 'الشفرة الجينية الرقمية', card2Desc: 'رقم تسلسلي <strong>فريد من 30 رقمًا</strong>.', card2Badge: '30 خانة', card3Title: 'BLOB SQL — سجلات غير قابلة للتغيير', card3Desc: 'مرتبطة بـ<strong>سلسلة تجزئة تشفيرية</strong>.', card3Badge: 'قابل للتحقق بأثر رجعي' },
  vision: { tag: 'انضم إلينا', title: 'نحول الزراعة إلى', title2: 'نظام بيئي بلا بشر وبلا هدر.', desc1: 'في NaT، نطور حلاً مستقلاً قائمًا على البيانات.', desc2: 'ندعو المستثمرين والشركاء للانضمام.', cta: 'تواصل مع فريق التأسيس' },
  footer: { ecosystem: 'النظام البيئي', company: 'الشركة', legal: 'قانوني', home: 'الرئيسية', career: 'الوظائف', contact: 'اتصل بنا', privacy: 'سياسة الخصوصية', kvkk: 'حماية البيانات', terms: 'شروط الاستخدام', copyright: '© 2026 NaT — Natural Agriculture Technologies. جميع الحقوق محفوظة.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'أرسل لنا رسالة!', infoTag: 'اتصل بنا', infoTitleHtml: 'لننقذ<br/>العالم<br/><span class="highlight-text"><b>معًا</b>!</span>', infoDesc: 'نحن هنا لجميع أسئلتكم.', emailLabel: 'البريد الإلكتروني', coFounder: 'شريك مؤسس ومالك', locationLabel: 'الموقع', location: 'تركيا', formTitle: 'أرسل رسالتك', nameField: 'الاسم الكامل', emailField: 'البريد الإلكتروني', nameError: 'حقل مطلوب.', emailError: 'أدخل بريدًا صالحًا.', orgToggleTitle: 'أكتب نيابة عن شركة', orgToggleDesc: 'شارك تفاصيل إضافية.', orgNameField: 'اسم الشركة', orgRoleField: 'المسمى الوظيفي', subjectLabel: 'الموضوع', subjectInvest: 'الاستثمار والتمويل', subjectPartner: 'الشراكة الاستراتيجية', subjectProduct: 'المنتج والتكنولوجيا', subjectCareer: 'الوظائف والفريق', subjectMedia: 'الإعلام والصحافة', subjectOther: 'أخرى', subjectError: 'اختر موضوعًا.', messageField: 'رسالتك', messageError: 'حقل مطلوب.', submitBtn: 'إرسال', submitting: 'جارٍ الإرسال…', privacyNote: 'معلوماتك آمنة.', successMsg: 'تم إرسال رسالتك!', errorMsg: 'حدث خطأ. حاول لاحقًا.', watermark: 'اتصل بنا' },
};
