import type { TranslationSet } from './types';
export const az: TranslationSet = {
  nav: { home: 'Ana Səhifə', problem: 'Problem', hardware: 'Avadanlıq', intelligence: 'Süni Zəka', operation: 'Əməliyyat', security: 'Təhlükəsizlik', join: 'Bizə Qoşul!', mobileToggle: 'Mobil menyu', mobileNav: 'Mobil naviqasiya', mainNav: 'Əsas naviqasiya' },
  hero: { subtitle: 'Qlobal su və qida böhranına qarşı; hər bitki üçün öz mikro-iqlimini simulyasiya edə bilən, RAG əsaslı və tam avtonom bir kənd təsərrüfatı ekosistemi qururuq.', exploreBtn: 'Vizyonumuzu Kəşf Et', pitchBtn: 'Pitch Deck Yüklə', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Qlobal Böhran', title: 'Problemi Bilirik. Həllini Qururuq.', desc: 'Dünya kənd təsərrüfatı iflas nöqtəsinə yaxınlaşır. <strong>2050-ci ildə 10 milyard insanı</strong> qidalandırmaq üçün istehsalı 60% artırmalıyıq — lakin hazırkı üsullarla bu mümkün deyil.', card1Title: 'Səssiz Fəlakət: Su İsrafı', card1Desc: 'Dünya şirin suyunun <strong>70%-i</strong> kənd təsərrüfatında istifadə olunur və yarısı buxarlanma və ya yanlış suvarma ilə itirilir.', card2Title: 'İqlim Zəifliyi', card2Desc: 'Ənənəvi əkinçilik təbiətin mərhəmətindədir. Gözlənilməz bir şaxta illik əməyi günlər ərzində məhv edə bilər.', card3Title: 'Məlumat Təcridliyi', card3Desc: 'Kənd təsərrüfatı məlumatları yerli və təcrid olunmuş qalır. Fermerlər eyni səhvləri kollektiv öyrənmə mexanizmi olmadan təkrarlayır.' },
  coreVision: { tag: 'Ekosistem Dizaynı', title: 'Hər Coğrafiyada, Hər Bitki Üçün\nMükəmməl Mikro-İqlim Simulyasiyası.', desc: 'NaT-da son məqsədimiz yalnız məlumat oxumayan, <strong>mühiti dəyişən</strong> reaktiv və avtonom bir sistem yaratmaqdır.', feat1Title: 'Dinamik Adaptasiya', feat1Desc: 'Tarlanızın harada olmasından asılı olmayaraq, sistem bitkilərin ani metabolik ehtiyaclarını oxuyur.', feat2Title: 'Dəqiq Əlavə Şəbəkəsi', feat2Desc: 'Yalnız lazım olduqda miqqram/millilitr dəqiqliyi ilə <strong>qida, su, istilik və gübrə</strong> təmin edir.', feat3Title: 'Avtonom Qərar Mexanizmi', feat3Desc: 'Bitki stresə düşmədən əvvəl, yerli iqlimin mənfi təsirlərini neytrallaşdırmaq üçün mikro-müdaxilələri <strong>avtomatik olaraq işə salır</strong>.' },
  hardware: { watermark: 'AVADANLIQ', tag: 'Avadanlıq Ar-Ge', title: 'Sahəyə Yerləşdiriləcək Zəka: sensSeries', desc: 'NaT ekosisteminin sinir ucları olacaq avadanlıq ailəmizi dizayn edirik.', sensTreeDesc: 'Ağacların bioloji proseslərini izləmək üçün birbaşa gövdəyə quraşdırılan möhkəm IoT cihazı.', sensSoilDesc: 'Torpağa asanlıqla nüfuz edən, NPK, pH və rütubəti ölçən kəskin dizaynlı yeraltı sensor.', sensPlantDesc: 'Fidelər üçün nəzərdə tutulmuş, simptomlar yaranmadan xəstəlikləri aşkar etmək üçün biokimyəvi dəyişiklikləri analiz edən klipsli cihaz.' },
  rag: { watermark: 'ZƏKA', tag: 'RAG Əsaslı Süni Zəka', title: 'Qlobal Təcrübə, Yerli Müdaxilə.', desc: 'Proqramçı komandamız LLM-lərin gücünü kənd təsərrüfatı verilənlər bazaları ilə birləşdirən RAG arxitekturası qurur.', pred1Title: 'Proaktiv Proqnoz', pred1Desc: 'NaT sahə məlumatlarını emal edərək "bu xəstəliyin riski 3 gündə 84%" deyə bilmək üçün öyrədilir.', pred2Title: 'Kollektiv Federativ Öyrənmə', pred2Desc: 'Hər NaT cihazı məxfiliyi qoruyaraq mərkəzi modeli öyrədir. Argentinada tapılmış strategiya Konyada saniyələr içində tətbiq olunur.' },
  operation: { watermark: 'ƏMƏLİYYAT', tag: 'Əməliyyat Vizyonu', title: 'Diaqnozdan Müalicəyə Avtonom Keçid', desc: 'Məlumat toplamaq işin yarısıdır. Əsas hədəfimiz bu məlumatı avtonom fiziki hərəkətə çevirməkdir.', card1Title: 'API İnteqrasiyası və Nöqtəvi Müdaxilə', card1Desc: 'Süni zəkamız qərar verdikdə, dronlara və ya avtonom sistemlərə birbaşa API vasitəsilə <strong>nöqtəvi müdaxilə</strong> əmrləri göndərir.', card2Title: 'Maksimal Məhsul, Minimum Kimya', card2Desc: 'Yalnız xəstələnmək üzrə olan xüsusi metrləri müalicə edərək kimyəvi istifadəni <strong>85%-ə qədər azaltmağı</strong> planlaşdırırıq.' },
  lab: { title: '4 Addımda', subtitle: 'Laboratoriya testlərindən daha uğurluyuq.', box1Title: 'Zaman İtkisi və Gecikmiş Reaksiya', box1Desc: 'Laboratoriya testləri böyük zaman itkisi yaradır. Nümunə alma və nəticələr günlər çəkir.', box2Title: 'Nümunə Yanılması və Təmsil Problemi', box2Desc: 'Bir ovuc torpaq bütöv bir sahəni təmsil edir. Amma torpaq strukturu heç vaxt homogen olmur.', box3Title: 'Ekosistem Ayrılması', box3Desc: 'Torpaq canlı bir ekosistemdir. Nümunə çıxarılan anda mikrobioloji strukturu pozulmağa başlayır.', box4Title: 'Statik Məlumat vs. Dinamik Axın', box4Desc: 'Laboratoriya testləri yalnız ani bir görüntü verir. Kənd təsərrüfatı daimi dinamik bir prosesdir.' },
  security: { watermark: 'TƏHLÜKƏSİZLİK', tag: 'Kiber Qalxan', title: 'Dəyişdirilməz Məlumat,', title2: 'Əlçatmaz Avadanlıq.', desc: 'NaT ekosistemi hərbi səviyyəli AES-256 şifrələmə ilə qorunur. Məlumatlarınız <strong>uçdan uca şifrələnir</strong>.', card1Title: 'Match-Lock Protokolu', card1Desc: 'Qoşulduqda cihaz istifadəçi hesabı ilə <strong>kriptoqrafik olaraq cütləşir</strong> və görünməz rejimə keçir.', card1Badge: 'Görünməz Rejim Aktiv', card2Title: 'Rəqəmsal Genetik Kod', card2Desc: 'Hər cihaz zavodda <strong>unikal 30 rəqəmli</strong> seriya nömrəsi ilə möhürlənir.', card2Badge: '30 Rəqəmli Seriya Nömrəsi', card3Title: 'BLOB SQL — Dəyişməz Qeydlər', card3Desc: 'Bütün qeydlər BLOB formatında saxlanılır və <strong>kriptoqrafik hash zənciri</strong> ilə birləşdirilir.', card3Badge: 'Geriyə Dönük Doğrulana Bilər' },
  vision: { tag: 'Bizə Qoşulun', title: 'Kənd Təsərrüfatını İnsansız və İsrafsız', title2: 'Bir Ekosistemə Çeviririk.', desc1: 'NaT-da qlobal kənd təsərrüfatı böhranına qarşı məlumat əsaslı və tam avtonom bir həll hazırlayırıq. Vizyonumuz: kənd təsərrüfatını xarici asılılıqlardan azad etmək.', desc2: 'Mələk investorları, strateji tərəfdaşları və innovasiya öncülərini sıralarımıza dəvət edirik.', cta: 'Qurucu Komanda ilə Əlaqə' },
  footer: { ecosystem: 'Ekosistem', company: 'Şirkət', legal: 'Hüquqi', home: 'Ana Səhifə', career: 'Karyera', contact: 'Əlaqə', privacy: 'Gizlilik Siyasəti', kvkk: 'Məlumat Qorunması', terms: 'İstifadə Şərtləri', copyright: '© 2026 NaT — Natural Agriculture Technologies. Bütün hüquqlar qorunur.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Bizə mesaj göndərin!', infoTag: 'Əlaqə', infoTitleHtml: 'Dünyanı<br/>birlikdə<br/><span class="highlight-text"><b>xilas edək</b>!</span>', infoDesc: 'İnvestisiya, əməkdaşlıq, karyera və ya məhsullarımız haqqında bütün suallarınız üçün buradayıq.', emailLabel: 'E-poçt', coFounder: 'Həmtəsisçi və Sahibi', locationLabel: 'Məkan', location: 'Türkiyə', formTitle: 'Mesajınızı Göndərin', nameField: 'Ad Soyad', emailField: 'E-poçt Ünvanı', nameError: 'Bu sahə tələb olunur.', emailError: 'Düzgün e-poçt daxil edin.', orgToggleTitle: 'Şirkət və ya təşkilat adından yazıram', orgToggleDesc: 'Korporativ mesajlar üçün əlavə məlumat paylaşın.', orgNameField: 'Şirkət / Təşkilat Adı', orgRoleField: 'Vəzifə / Mövqe', subjectLabel: 'Mövzu', subjectInvest: 'İnvestisiya & Maliyyə', subjectPartner: 'Strateji Tərəfdaşlıq', subjectProduct: 'Məhsul & Texnologiya', subjectCareer: 'Karyera & Komanda', subjectMedia: 'Media & Mətbuat', subjectOther: 'Digər', subjectError: 'Mövzu seçin.', messageField: 'Mesajınız', messageError: 'Mesaj sahəsi tələb olunur.', submitBtn: 'Göndər', submitting: 'Göndərilir…', privacyNote: 'Məlumatlarınız təhlükəsizdir və üçüncü tərəflərlə paylaşılmayacaq.', successMsg: 'Mesajınız uğurla göndərildi!', errorMsg: 'Xəta baş verdi. Daha sonra yenidən cəhd edin.', watermark: 'ƏLAQƏ' },
};
