import type { TranslationSet } from './types';
export const az: TranslationSet = {
  nav: { home: 'Ana Səhifə', problem: 'Problem', hardware: 'Avadanlıq', intelligence: 'Süni Zəka', operation: 'Əməliyyat', security: 'Təhlükəsizlik', join: 'Bizə Qoşul!', mobileToggle: 'Mobil menyu', mobileNav: 'Mobil naviqasiya', mainNav: 'Əsas naviqasiya' },
  hero: { subtitle: 'Qlobal su və qida böhranına qarşı hər bitki üçün öz mikro-iqlimini simulyasiya edə bilən, RAG əsaslı tam avtonom bir kənd təsərrüfatı ekosistemi qururuq.', exploreBtn: 'Vizyonumuzu Kəşf Et', pitchBtn: 'Pitch Deck Yüklə', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Qlobal Böhran', title: 'Problemi Bilirik. Həllini Qururuq.', desc: '<strong>2050-ci ildə 10 milyard insanı</strong> qidalandırmaq üçün istehsalı 60% artırmalıyıq.', card1Title: 'Səssiz Fəlakət: Su İsrafı', card1Desc: 'Şirin suyun <strong>70%-i</strong> kənd təsərrüfatında istifadə olunur.', card2Title: 'İqlim Zəifliyi', card2Desc: 'Ənənəvi əkinçilik təbiətin mərhəmətindədir.', card3Title: 'Məlumat Təcridliyi', card3Desc: 'Kənd təsərrüfatı məlumatları yerli və təcrid olunmuş qalır.' },
  coreVision: { tag: 'Ekosistem Dizaynı', title: 'Hər Bitki Üçün Mükəmməl\nMikro-İqlim Simulyasiyası.', desc: '<strong>Mühiti dəyişən</strong> reaktiv və avtonom bir sistem yaratmaq.', feat1Title: 'Dinamik Adaptasiya', feat1Desc: 'Sistem bitkilərin ani metabolik ehtiyaclarını oxuyur.', feat2Title: 'Dəqiq Əlavə Şəbəkəsi', feat2Desc: 'Miqqram dəqiqliyi ilə <strong>qida, su, istilik və gübrə</strong> təmin edir.', feat3Title: 'Avtonom Qərar Mexanizmi', feat3Desc: '<strong>Avtomatik olaraq</strong> mikro-müdaxilələri işə salır.' },
  hardware: { watermark: 'AVADANLIQ', tag: 'Avadanlıq Ar-Ge', title: 'Sahəyə Yerləşdiriləcək Zəka: sensSeries', desc: 'NaT ekosisteminin sinir ucları olacaq avadanlıq ailəmizi dizayn edirik.', sensTreeDesc: 'Gövdəyə quraşdırılan IoT cihazı.', sensSoilDesc: 'Torpağa nüfuz edən yeraltı sensor.', sensPlantDesc: 'Fidelər üçün klipsli cihaz.' },
  rag: { watermark: 'ZƏKA', tag: 'RAG Əsaslı Süni Zəka', title: 'Qlobal Təcrübə, Yerli Müdaxilə.', desc: 'LLM-lərin gücünü kənd təsərrüfatı verilənlər bazaları ilə birləşdirən RAG arxitekturası.', pred1Title: 'Proaktiv Proqnoz', pred1Desc: 'NaT proqnozlaşdırır: "bu xəstəliyin riski 3 gündə 84%."', pred2Title: 'Kollektiv Federativ Öyrənmə', pred2Desc: 'Hər cihaz məxfiliyi qoruyaraq mərkəzi modeli öyrədir.' },
  operation: { watermark: 'ƏMƏLİYYAT', tag: 'Əməliyyat Vizyonu', title: 'Diaqnozdan Müalicəyə Avtonom Keçid', desc: 'Əsas hədəfimiz məlumatı avtonom fiziki hərəkətə çevirməkdir.', card1Title: 'API İnteqrasiyası', card1Desc: 'Süni zəkamız <strong>nöqtəvi müdaxilə</strong> əmrləri göndərir.', card2Title: 'Maksimal Məhsul', card2Desc: 'Kimyəvi istifadəni <strong>85%-ə qədər azaltmağı</strong> planlaşdırırıq.' },
  lab: { title: '4 Addımda', subtitle: 'Laboratoriya testlərindən daha uğurluyuq.', box1Title: 'Zaman İtkisi', box1Desc: 'Nümunə alma və nəticələr günlər çəkir.', box2Title: 'Nümunə Yanılması', box2Desc: 'Bir ovuc torpaq bütöv sahəni təmsil edir.', box3Title: 'Ekosistem Ayrılması', box3Desc: 'Nümunə çıxarılan anda mikrobioloji struktur pozulur.', box4Title: 'Statik vs. Dinamik', box4Desc: 'Laboratoriya testləri yalnız ani görüntü verir.' },
  security: { watermark: 'TƏHLÜKƏSİZLİK', tag: 'Kiber Qalxan', title: 'Dəyişdirilməz Məlumat,', title2: 'Əlçatmaz Avadanlıq.', desc: 'Məlumatlarınız <strong>uçdan uca şifrələnir</strong>.', card1Title: 'Match-Lock Protokolu', card1Desc: 'Cihaz <strong>kriptoqrafik olaraq cütləşir</strong>.', card1Badge: 'Görünməz Rejim', card2Title: 'Rəqəmsal Genetik Kod', card2Desc: '<strong>Unikal 30 rəqəmli</strong> seriya nömrəsi.', card2Badge: '30 Rəqəmli Nömrə', card3Title: 'BLOB SQL — Dəyişməz Qeydlər', card3Desc: '<strong>Kriptoqrafik hash zənciri</strong> ilə birləşdirilir.', card3Badge: 'Geriyə Dönük Doğrulana Bilər' },
  vision: { tag: 'Bizə Qoşulun', title: 'Kənd Təsərrüfatını İnsansız və İsrafsız', title2: 'Bir Ekosistemə Çeviririk.', desc1: 'NaT-da qlobal böhrana qarşı məlumat əsaslı həll hazırlayırıq.', desc2: 'Mələk investorları və strateji tərəfdaşları dəvət edirik.', cta: 'Qurucu Komanda ilə Əlaqə' },
  footer: { ecosystem: 'Ekosistem', company: 'Şirkət', legal: 'Hüquqi', home: 'Ana Səhifə', career: 'Karyera', contact: 'Əlaqə', privacy: 'Gizlilik Siyasəti', kvkk: 'Məlumat Qorunması', terms: 'İstifadə Şərtləri', copyright: '© 2026 NaT — Natural Agriculture Technologies. Bütün hüquqlar qorunur.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Bizə mesaj göndərin!', infoTag: 'Əlaqə', infoTitleHtml: 'Dünyanı<br/>birlikdə<br/><span class="highlight-text"><b>xilas edək</b>!</span>', infoDesc: 'Bütün suallarınız üçün buradayıq.', emailLabel: 'E-poçt', coFounder: 'Həmtəsisçi və Sahibi', locationLabel: 'Məkan', location: 'Türkiyə', formTitle: 'Mesajınızı Göndərin', nameField: 'Ad Soyad', emailField: 'E-poçt Ünvanı', nameError: 'Bu sahə tələb olunur.', emailError: 'Düzgün e-poçt daxil edin.', orgToggleTitle: 'Şirkət adından yazıram', orgToggleDesc: 'Əlavə məlumat paylaşın.', orgNameField: 'Şirkət Adı', orgRoleField: 'Vəzifə', subjectLabel: 'Mövzu', subjectInvest: 'İnvestisiya & Maliyyə', subjectPartner: 'Strateji Tərəfdaşlıq', subjectProduct: 'Məhsul & Texnologiya', subjectCareer: 'Karyera & Komanda', subjectMedia: 'Media & Mətbuat', subjectOther: 'Digər', subjectError: 'Mövzu seçin.', messageField: 'Mesajınız', messageError: 'Mesaj sahəsi tələb olunur.', submitBtn: 'Göndər', submitting: 'Göndərilir…', privacyNote: 'Məlumatlarınız təhlükəsizdir.', successMsg: 'Mesajınız uğurla göndərildi!', errorMsg: 'Xəta baş verdi. Daha sonra yenidən cəhd edin.', watermark: 'ƏLAQƏ' },
};
