import type { TranslationSet } from './types';
export const de: TranslationSet = {
  nav: { home: 'Startseite', problem: 'Problem', hardware: 'Hardware', intelligence: 'Intelligenz', operation: 'Betrieb', security: 'Sicherheit', join: 'Mitmachen!', mobileToggle: 'Mobiles Menü', mobileNav: 'Mobile Navigation', mainNav: 'Hauptnavigation' },
  hero: { subtitle: 'Gegen die globale Wasser- und Nahrungsmittelkrise bauen wir ein vollautonomes, RAG-basiertes landwirtschaftliches Ökosystem.', exploreBtn: 'Unsere Vision Entdecken', pitchBtn: 'Pitch Deck Herunterladen', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Globale Krise', title: 'Wir Kennen das Problem. Wir Bauen die Lösung.', desc: 'Die globale Landwirtschaft nähert sich dem Kollaps. Um <strong>10 Milliarden Menschen bis 2050</strong> zu ernähren, müssen wir die Produktion um 60% steigern.', card1Title: 'Stille Katastrophe: Wasserverschwendung', card1Desc: '<strong>70%</strong> des Süßwassers wird in der Landwirtschaft verwendet, die Hälfte geht verloren.', card2Title: 'Klimaverwundbarkeit', card2Desc: 'Konventionelle Landwirtschaft ist der Natur ausgeliefert.', card3Title: 'Datenisolierung', card3Desc: 'Landwirtschaftliche Daten bleiben lokal und isoliert.' },
  coreVision: { tag: 'Ökosystem-Design', title: 'Perfekte Mikroklima-Simulation\nfür Jede Pflanze, Überall.', desc: 'Bei NaT ist unser Ziel ein System, das Daten nicht nur liest — es <strong>verändert die Umgebung</strong>.', feat1Title: 'Dynamische Anpassung', feat1Desc: 'Das System liest die sofortigen metabolischen Bedürfnisse der Pflanzen.', feat2Title: 'Präzises Ergänzungsnetzwerk', feat2Desc: 'Liefert <strong>Nährstoffe, Wasser, Wärme und Dünger</strong> mit Milligramm-Genauigkeit.', feat3Title: 'Autonomer Entscheidungsmotor', feat3Desc: '<strong>Löst automatisch</strong> Mikro-Interventionen aus.' },
  hardware: { watermark: 'HARDWARE', tag: 'Hardware-F&E', title: 'Im Feld Eingebettete Intelligenz: sensSeries', desc: 'Wir entwickeln die Hardware-Familie, die als Nervenenden des NaT-Ökosystems dienen wird.', sensTreeDesc: 'Ein robustes IoT-Gerät, das direkt am Stamm montiert wird.', sensSoilDesc: 'Ein unterirdischer Sensor mit scharfem Design für Bodenpenetration.', sensPlantDesc: 'Ein Clip-Tracking-Gerät für Setzlinge.' },
  rag: { watermark: 'INTELLIGENZ', tag: 'RAG-basierte KI', title: 'Globale Erfahrung, Lokale Aktion.', desc: 'Unser Team baut eine RAG-Architektur, die LLMs mit landwirtschaftlichen Datenbanken kombiniert.', pred1Title: 'Proaktive Vorhersage', pred1Desc: 'NaT wird trainiert, „Diese Krankheit hat ein 84%-Risiko in 3 Tagen" vorherzusagen.', pred2Title: 'Kollektives Föderiertes Lernen', pred2Desc: 'Jedes NaT-Gerät trainiert das zentrale Modell unter Wahrung der Privatsphäre.' },
  operation: { watermark: 'BETRIEB', tag: 'Operative Vision', title: 'Autonomer Übergang von Diagnose zu Behandlung', desc: 'Unser Ziel: Daten in autonome physische Aktion umwandeln.', card1Title: 'API-Integration und Gezielte Intervention', card1Desc: 'Unsere KI sendet <strong>gezielte Interventions</strong>-Befehle direkt an Drohnen.', card2Title: 'Maximaler Ertrag, Minimale Chemie', card2Desc: 'Chemikalieneinsatz <strong>um bis zu 85%</strong> reduziert.' },
  lab: { title: 'In 4 Schritten', subtitle: 'Wir übertreffen Labortests.', box1Title: 'Zeitverlust', box1Desc: 'Probenahme und Ergebnisse dauern Tage.', box2Title: 'Stichprobenfehler', box2Desc: 'Eine Handvoll Erde repräsentiert ein ganzes Feld.', box3Title: 'Ökosystem-Trennung', box3Desc: 'Bei Probenahme beginnt der mikrobiologische Abbau.', box4Title: 'Statische Daten vs. Dynamischer Fluss', box4Desc: 'Labortests liefern nur eine Momentaufnahme.' },
  security: { watermark: 'SICHERHEIT', tag: 'Cyber-Schild', title: 'Unveränderliche Daten,', title2: 'Unzugängliche Hardware.', desc: 'Ihre Daten sind <strong>Ende-zu-Ende verschlüsselt</strong>.', card1Title: 'Match-Lock-Protokoll', card1Desc: 'Das Gerät wird <strong>kryptografisch gepaart</strong>.', card1Badge: 'Stealth-Modus Aktiv', card2Title: 'Digitaler Genetischer Code', card2Desc: '<strong>Einzigartige 30-stellige</strong> Seriennummer.', card2Badge: '30-Stellige Seriennummer', card3Title: 'BLOB SQL — Unveränderliche Aufzeichnungen', card3Desc: 'Durch eine <strong>kryptografische Hash-Kette</strong> verknüpft.', card3Badge: 'Rückwirkend Verifizierbar' },
  vision: { tag: 'Mitmachen', title: 'Landwirtschaft Transformieren in ein', title2: 'Menschenloses, Abfallfreies Ökosystem.', desc1: 'Bei NaT entwickeln wir eine vollautonome Lösung für die globale Agrarkrise.', desc2: 'Wir laden Angel-Investoren, strategische Partner und Innovationspioniere ein.', cta: 'Gründerteam Kontaktieren' },
  footer: { ecosystem: 'Ökosystem', company: 'Unternehmen', legal: 'Rechtliches', home: 'Startseite', career: 'Karriere', contact: 'Kontakt', privacy: 'Datenschutzrichtlinie', kvkk: 'Datenschutz', terms: 'Nutzungsbedingungen', copyright: '© 2026 NaT — Natural Agriculture Technologies. Alle Rechte vorbehalten.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Senden Sie uns eine Nachricht!', infoTag: 'Kontakt', infoTitleHtml: 'Retten wir<br/>die Welt<br/><span class="highlight-text"><b>gemeinsam</b>!</span>', infoDesc: 'Wir sind hier für alle Ihre Fragen.', emailLabel: 'E-Mail', coFounder: 'Mitgründer & Inhaber', locationLabel: 'Standort', location: 'Türkei', formTitle: 'Ihre Nachricht Senden', nameField: 'Vollständiger Name', emailField: 'E-Mail-Adresse', nameError: 'Dieses Feld ist erforderlich.', emailError: 'Bitte gültige E-Mail eingeben.', orgToggleTitle: 'Ich schreibe im Namen eines Unternehmens', orgToggleDesc: 'Teilen Sie zusätzliche Details.', orgNameField: 'Unternehmen / Organisation', orgRoleField: 'Titel / Position', subjectLabel: 'Betreff', subjectInvest: 'Investition & Finanzen', subjectPartner: 'Strategische Partnerschaft', subjectProduct: 'Produkt & Technologie', subjectCareer: 'Karriere & Team', subjectMedia: 'Medien & Presse', subjectOther: 'Sonstiges', subjectError: 'Bitte Betreff wählen.', messageField: 'Ihre Nachricht', messageError: 'Nachrichtenfeld ist erforderlich.', submitBtn: 'Senden', submitting: 'Wird gesendet…', privacyNote: 'Ihre Informationen sind sicher.', successMsg: 'Ihre Nachricht wurde erfolgreich gesendet!', errorMsg: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.', watermark: 'KONTAKT' },
};
