import type { TranslationSet } from './types';
export const en: TranslationSet = {
  nav: { home: 'Home', problem: 'Problem', hardware: 'Hardware', intelligence: 'Intelligence', operation: 'Operation', security: 'Security', join: 'Join Us!', mobileToggle: 'Toggle mobile menu', mobileNav: 'Mobile navigation', mainNav: 'Main navigation' },
  hero: { subtitle: 'Against the global water and food crisis, we are building a fully autonomous, RAG-based agricultural ecosystem capable of simulating its own micro-climate for every plant.', exploreBtn: 'Explore Our Vision', pitchBtn: 'Download Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Global Crisis', title: 'We Know the Problem. We Are Building the Solution.', desc: 'Global agriculture is approaching collapse. To feed <strong>10 billion people by 2050</strong>, we must increase production by 60% — yet this is impossible with current methods, depleted water resources, and unpredictable climate crises.', card1Title: 'Silent Catastrophe: Water & Nutrient Waste', card1Desc: '<strong>70%</strong> of the world\'s fresh water is used in agriculture, and half is lost to evaporation, incorrect irrigation, or leakage.', card2Title: 'Climate Vulnerability', card2Desc: 'Conventional farming is at the mercy of nature. An unexpected frost, extreme heat, or drought can destroy a year\'s work within days.', card3Title: 'Data Isolation', card3Desc: 'Agricultural data remains local and isolated. Farmers repeat the same mistakes because there is no collective learning mechanism.' },
  coreVision: { tag: 'Ecosystem Design', title: 'Perfect Micro-Climate Simulation\nfor Every Plant, Everywhere.', desc: 'At NaT, our ultimate goal is to create a reactive and autonomous system that doesn\'t just read data — it <strong>changes the environment</strong>.', feat1Title: 'Dynamic Adaptation', feat1Desc: 'Regardless of where your field is located, the system reads the immediate metabolic needs of the current plants.', feat2Title: 'Precision Supplement Network', feat2Desc: 'Delivers <strong>nutrients, water, heat, and fertilizer</strong> with milligram/milliliter precision, only when needed.', feat3Title: 'Autonomous Decision Engine', feat3Desc: 'Before the plant experiences stress, it <strong>automatically triggers</strong> micro-interventions to neutralize adverse climate effects.' },
  hardware: { watermark: 'HARDWARE', tag: 'Hardware R&D', title: 'Intelligence Embedded in the Field: sensSeries', desc: 'We are designing the hardware family that will serve as the nerve endings of the NaT ecosystem — maximum data, minimum energy.', sensTreeDesc: 'A robust, industrially designed IoT device mounted directly onto the trunk to monitor biological processes of trees.', sensSoilDesc: 'An underground sensor with a sharp, wedge-shaped design for easy soil penetration, measuring NPK, pH, and moisture.', sensPlantDesc: 'A clip-on tracking device for seedlings, analyzing biochemical changes to detect diseases before symptoms appear.' },
  rag: { watermark: 'INTELLIGENCE', tag: 'RAG-Based AI', title: 'Global Experience, Local Action.', desc: 'Our software team is building a RAG-based architecture combining the power of large language models with agricultural databases.', pred1Title: 'Proactive Prediction', pred1Desc: 'NaT is being trained to process raw field data and predict: "this disease has an 84% risk in 3 days."', pred2Title: 'Collective Federated Learning', pred2Desc: 'Every deployed NaT device trains the central model while preserving privacy. A strategy found in Argentina is applied in Konya within seconds.' },
  operation: { watermark: 'OPERATION', tag: 'Operational Vision', title: 'Autonomous Transition from Diagnosis to Treatment', desc: 'Collecting data is only half the job. Our real goal is turning data into autonomous physical action.', card1Title: 'API Integration & Targeted Intervention', card1Desc: 'When our AI decides, it sends <strong>targeted intervention</strong> commands directly via API to drones or autonomous systems.', card2Title: 'Maximum Yield, Minimum Chemicals', card2Desc: 'We treat only the specific square meters about to get sick — reducing chemical use by <strong>up to 85%</strong>.' },
  lab: { title: 'In 4 Steps', subtitle: 'We outperform laboratory tests.', box1Title: 'Time Loss & Delayed Response', box1Desc: 'Lab tests create enormous time loss. Taking a soil sample, transferring it, and getting results typically takes days.', box2Title: 'Sample Bias & Representation', box2Desc: 'Only a few handfuls of soil are sent to represent an entire field. But soil structure is never homogeneous.', box3Title: 'Ecosystem Disconnect', box3Desc: 'Soil is a living ecosystem. The moment a sample is uprooted, its microbiological structure begins to degrade.', box4Title: 'Static Data vs. Dynamic Flow', box4Desc: 'Lab tests provide only a static snapshot. Agriculture is a constantly evolving dynamic process.' },
  security: { watermark: 'SECURITY', tag: 'Cyber Shield', title: 'Immutable Data,', title2: 'Inaccessible Hardware.', desc: 'The NaT ecosystem is protected by military-grade AES-256 encryption and hardware-based authentication. Your data is <strong>encrypted end-to-end</strong>.', card1Title: 'Match-Lock Protocol', card1Desc: 'When first connected, the device is <strong>cryptographically paired</strong> with the user account and enters invisible mode.', card1Badge: 'Stealth Mode Active', card2Title: 'Digital Genetic Code', card2Desc: 'Each device is factory-sealed with a <strong>unique 30-digit</strong> serial number.', card2Badge: '30-Digit Serial Number', card3Title: 'BLOB SQL — Immutable Records', card3Desc: 'All records are stored in BLOB format and linked with a <strong>cryptographic hash chain</strong>.', card3Badge: 'Retroactively Verifiable' },
  vision: { tag: 'Join Us', title: 'Transforming Agriculture into a', title2: 'Humanless, Waste-Free Ecosystem.', desc1: 'At NaT, we are developing a data-driven, fully autonomous solution to the global agricultural crisis. Our vision: liberate agriculture from external dependencies.', desc2: 'We invite angel investors, strategic partners, and innovation pioneers to join our ranks.', cta: 'Contact the Founding Team' },
  footer: { ecosystem: 'Ecosystem', company: 'Company', legal: 'Legal', home: 'Home', career: 'Career', contact: 'Contact', privacy: 'Privacy Policy', kvkk: 'Data Protection', terms: 'Terms of Use', copyright: '© 2026 NaT — Natural Agriculture Technologies. All rights reserved.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Send us a message!', infoTag: 'Contact', infoTitleHtml: 'Let\'s save<br/>the world<br/><span class="highlight-text"><b>together</b>!</span>', infoDesc: 'We are here for all your questions about investment, collaboration, career, or our products.', emailLabel: 'Email', coFounder: 'Co-Founder & Owner', locationLabel: 'Location', location: 'Turkey', formTitle: 'Send Your Message', nameField: 'Full Name', emailField: 'Email Address', nameError: 'This field is required.', emailError: 'Please enter a valid email.', orgToggleTitle: 'I am writing on behalf of a company or organization', orgToggleDesc: 'Share additional details for corporate messages.', orgNameField: 'Company / Organization Name', orgRoleField: 'Title / Position', subjectLabel: 'Subject', subjectInvest: 'Investment & Finance', subjectPartner: 'Strategic Partnership', subjectProduct: 'Product & Technology', subjectCareer: 'Career & Team', subjectMedia: 'Media & Press', subjectOther: 'Other', subjectError: 'Please select a subject.', messageField: 'Your Message', messageError: 'Message field is required.', submitBtn: 'Send', submitting: 'Sending…', privacyNote: 'Your information is safe and will not be shared with third parties.', successMsg: 'Your message has been sent successfully!', errorMsg: 'An error occurred. Please try again later.', watermark: 'CONTACT' },
};
