import type { TranslationSet } from './types';
export const es: TranslationSet = {
  nav: { home: 'Inicio', problem: 'Problema', hardware: 'Hardware', intelligence: 'Inteligencia', operation: 'Operación', security: 'Seguridad', join: '¡Únete!', mobileToggle: 'Menú móvil', mobileNav: 'Navegación móvil', mainNav: 'Navegación principal' },
  hero: { subtitle: 'Contra la crisis global del agua y los alimentos, estamos construyendo un ecosistema agrícola totalmente autónomo basado en RAG, capaz de simular su propio microclima para cada planta.', exploreBtn: 'Explora Nuestra Visión', pitchBtn: 'Descargar Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Crisis Global', title: 'Conocemos el Problema. Estamos Construyendo la Solución.', desc: 'La agricultura mundial se acerca al colapso. Para alimentar a <strong>10 mil millones de personas en 2050</strong>, debemos aumentar la producción un 60%.', card1Title: 'Catástrofe Silenciosa: Desperdicio de Agua', card1Desc: 'El <strong>70%</strong> del agua dulce del mundo se usa en agricultura, y la mitad se pierde por evaporación.', card2Title: 'Vulnerabilidad Climática', card2Desc: 'La agricultura convencional está a merced de la naturaleza. Una helada inesperada puede destruir el trabajo de un año.', card3Title: 'Aislamiento de Datos', card3Desc: 'Los datos agrícolas permanecen locales y aislados. Los agricultores repiten los mismos errores.' },
  coreVision: { tag: 'Diseño del Ecosistema', title: 'Simulación de Microclima Perfecto\npara Cada Planta, en Todas Partes.', desc: 'En NaT, nuestro objetivo es crear un sistema reactivo y autónomo que no solo lee datos — <strong>cambia el entorno</strong>.', feat1Title: 'Adaptación Dinámica', feat1Desc: 'Sin importar dónde esté su campo, el sistema lee las necesidades metabólicas inmediatas de las plantas.', feat2Title: 'Red de Suplementación Precisa', feat2Desc: 'Suministra <strong>nutrientes, agua, calor y fertilizante</strong> con precisión de miligramos, solo cuando es necesario.', feat3Title: 'Motor de Decisión Autónomo', feat3Desc: 'Antes de que la planta sufra estrés, <strong>activa automáticamente</strong> micro-intervenciones.' },
  hardware: { watermark: 'HARDWARE', tag: 'I+D Hardware', title: 'Inteligencia Integrada en el Campo: sensSeries', desc: 'Estamos diseñando la familia de hardware que servirá como terminaciones nerviosas del ecosistema NaT.', sensTreeDesc: 'Un dispositivo IoT robusto montado directamente en el tronco para monitorear los procesos biológicos de los árboles.', sensSoilDesc: 'Un sensor subterráneo con diseño afilado para penetración fácil del suelo, midiendo NPK, pH y humedad.', sensPlantDesc: 'Un dispositivo de seguimiento tipo clip para plántulas, analizando cambios bioquímicos.' },
  rag: { watermark: 'INTELIGENCIA', tag: 'IA Basada en RAG', title: 'Experiencia Global, Acción Local.', desc: 'Nuestro equipo construye una arquitectura RAG que combina modelos de lenguaje con bases de datos agrícolas.', pred1Title: 'Predicción Proactiva', pred1Desc: 'NaT se entrena para procesar datos de campo y predecir: "esta enfermedad tiene un 84% de riesgo en 3 días."', pred2Title: 'Aprendizaje Federado Colectivo', pred2Desc: 'Cada dispositivo NaT entrena el modelo central preservando la privacidad.' },
  operation: { watermark: 'OPERACIÓN', tag: 'Visión Operacional', title: 'Transición Autónoma del Diagnóstico al Tratamiento', desc: 'Recopilar datos es solo la mitad. Nuestro objetivo real es convertir datos en acción física autónoma.', card1Title: 'Integración API e Intervención Dirigida', card1Desc: 'Cuando nuestra IA decide, envía comandos de <strong>intervención dirigida</strong> directamente a drones o sistemas autónomos.', card2Title: 'Máximo Rendimiento, Mínimos Químicos', card2Desc: 'Tratamos solo los metros cuadrados específicos, reduciendo el uso de químicos <strong>hasta un 85%</strong>.' },
  lab: { title: 'En 4 Pasos', subtitle: 'Superamos las pruebas de laboratorio.', box1Title: 'Pérdida de Tiempo', box1Desc: 'Las pruebas de laboratorio crean una enorme pérdida de tiempo.', box2Title: 'Sesgo de Muestras', box2Desc: 'Solo unos puñados de tierra representan un campo entero.', box3Title: 'Desconexión del Ecosistema', box3Desc: 'El suelo es un ecosistema vivo. Al extraer una muestra, su estructura comienza a degradarse.', box4Title: 'Datos Estáticos vs. Flujo Dinámico', box4Desc: 'Las pruebas solo ofrecen una instantánea. La agricultura es un proceso dinámico.' },
  security: { watermark: 'SEGURIDAD', tag: 'Escudo Cibernético', title: 'Datos Inmutables,', title2: 'Hardware Inaccesible.', desc: 'El ecosistema NaT está protegido con cifrado AES-256 de grado militar. Sus datos están <strong>cifrados de extremo a extremo</strong>.', card1Title: 'Protocolo Match-Lock', card1Desc: 'Al conectarse, el dispositivo se <strong>empareja criptográficamente</strong> con la cuenta del usuario.', card1Badge: 'Modo Invisible Activo', card2Title: 'Código Genético Digital', card2Desc: 'Cada dispositivo se sella en fábrica con un número de serie <strong>único de 30 dígitos</strong>.', card2Badge: 'Serie de 30 Dígitos', card3Title: 'BLOB SQL — Registros Inmutables', card3Desc: 'Todos los registros se enlazan con una <strong>cadena hash criptográfica</strong>.', card3Badge: 'Verificable Retroactivamente' },
  vision: { tag: 'Únete', title: 'Transformando la Agricultura en un', title2: 'Ecosistema Sin Humanos y Sin Desperdicio.', desc1: 'En NaT, desarrollamos una solución autónoma y basada en datos para la crisis agrícola global.', desc2: 'Invitamos a inversores ángeles, socios estratégicos y pioneros de la innovación.', cta: 'Contactar al Equipo Fundador' },
  footer: { ecosystem: 'Ecosistema', company: 'Empresa', legal: 'Legal', home: 'Inicio', career: 'Carrera', contact: 'Contacto', privacy: 'Política de Privacidad', kvkk: 'Protección de Datos', terms: 'Términos de Uso', copyright: '© 2026 NaT — Natural Agriculture Technologies. Todos los derechos reservados.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: '¡Envíanos un mensaje!', infoTag: 'Contacto', infoTitleHtml: 'Salvemos<br/>el mundo<br/><span class="highlight-text"><b>juntos</b>!</span>', infoDesc: 'Estamos aquí para todas sus preguntas sobre inversión, colaboración, carrera o nuestros productos.', emailLabel: 'Correo', coFounder: 'Co-Fundador y Propietario', locationLabel: 'Ubicación', location: 'Turquía', formTitle: 'Envíe Su Mensaje', nameField: 'Nombre Completo', emailField: 'Correo Electrónico', nameError: 'Este campo es obligatorio.', emailError: 'Ingrese un correo válido.', orgToggleTitle: 'Escribo en nombre de una empresa', orgToggleDesc: 'Comparta detalles adicionales.', orgNameField: 'Nombre de Empresa', orgRoleField: 'Cargo / Posición', subjectLabel: 'Asunto', subjectInvest: 'Inversión y Finanzas', subjectPartner: 'Asociación Estratégica', subjectProduct: 'Producto y Tecnología', subjectCareer: 'Carrera y Equipo', subjectMedia: 'Medios y Prensa', subjectOther: 'Otro', subjectError: 'Seleccione un asunto.', messageField: 'Su Mensaje', messageError: 'El campo de mensaje es obligatorio.', submitBtn: 'Enviar', submitting: 'Enviando…', privacyNote: 'Su información está segura.', successMsg: '¡Su mensaje ha sido enviado exitosamente!', errorMsg: 'Ocurrió un error. Intente de nuevo más tarde.', watermark: 'CONTACTO' },
};
