import type { TranslationSet } from './types';
export const fr: TranslationSet = {
  nav: { home: 'Accueil', problem: 'Problème', hardware: 'Matériel', intelligence: 'Intelligence', operation: 'Opération', security: 'Sécurité', join: 'Rejoignez-nous !', mobileToggle: 'Menu mobile', mobileNav: 'Navigation mobile', mainNav: 'Navigation principale' },
  hero: { subtitle: 'Face à la crise mondiale de l\'eau et de l\'alimentation, nous construisons un écosystème agricole entièrement autonome basé sur RAG.', exploreBtn: 'Découvrir Notre Vision', pitchBtn: 'Télécharger le Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Crise Mondiale', title: 'Nous Connaissons le Problème. Nous Construisons la Solution.', desc: 'L\'agriculture mondiale approche de l\'effondrement. Pour nourrir <strong>10 milliards de personnes d\'ici 2050</strong>, nous devons augmenter la production de 60%.', card1Title: 'Catastrophe Silencieuse : Gaspillage d\'Eau', card1Desc: '<strong>70%</strong> de l\'eau douce est utilisée en agriculture, la moitié est perdue.', card2Title: 'Vulnérabilité Climatique', card2Desc: 'L\'agriculture conventionnelle est à la merci de la nature.', card3Title: 'Isolation des Données', card3Desc: 'Les données agricoles restent locales et isolées.' },
  coreVision: { tag: 'Conception Écosystémique', title: 'Simulation Parfaite de Microclimat\npour Chaque Plante, Partout.', desc: 'Chez NaT, notre objectif est de créer un système qui <strong>modifie l\'environnement</strong>.', feat1Title: 'Adaptation Dynamique', feat1Desc: 'Le système lit les besoins métaboliques immédiats des plantes.', feat2Title: 'Réseau de Supplémentation Précis', feat2Desc: 'Fournit <strong>nutriments, eau, chaleur et engrais</strong> avec précision.', feat3Title: 'Moteur de Décision Autonome', feat3Desc: '<strong>Déclenche automatiquement</strong> des micro-interventions pour neutraliser les effets climatiques.' },
  hardware: { watermark: 'MATÉRIEL', tag: 'R&D Matériel', title: 'Intelligence Intégrée au Terrain : sensSeries', desc: 'Nous concevons la famille de matériel qui servira de terminaisons nerveuses de l\'écosystème NaT.', sensTreeDesc: 'Un dispositif IoT robuste monté sur le tronc pour surveiller les processus biologiques.', sensSoilDesc: 'Un capteur souterrain pour pénétration facile du sol, mesurant NPK, pH et humidité.', sensPlantDesc: 'Un dispositif à clip pour les semis, analysant les changements biochimiques.' },
  rag: { watermark: 'INTELLIGENCE', tag: 'IA Basée sur RAG', title: 'Expérience Globale, Action Locale.', desc: 'Notre équipe construit une architecture RAG combinant LLM avec des bases de données agricoles.', pred1Title: 'Prédiction Proactive', pred1Desc: 'NaT est formé pour prédire : « cette maladie a un risque de 84% dans 3 jours. »', pred2Title: 'Apprentissage Fédéré Collectif', pred2Desc: 'Chaque dispositif entraîne le modèle central en préservant la confidentialité.' },
  operation: { watermark: 'OPÉRATION', tag: 'Vision Opérationnelle', title: 'Transition Autonome du Diagnostic au Traitement', desc: 'Notre vrai objectif : transformer les données en action physique autonome.', card1Title: 'Intégration API et Intervention Ciblée', card1Desc: 'Notre IA envoie des commandes d\'<strong>intervention ciblée</strong> aux drones.', card2Title: 'Rendement Maximum, Minimum de Chimie', card2Desc: 'Réduction de l\'utilisation de produits chimiques <strong>jusqu\'à 85%</strong>.' },
  lab: { title: 'En 4 Étapes', subtitle: 'Nous surpassons les tests de laboratoire.', box1Title: 'Perte de Temps', box1Desc: 'L\'échantillonnage et les résultats prennent des jours.', box2Title: 'Biais d\'Échantillonnage', box2Desc: 'Quelques poignées de terre représentent un champ entier.', box3Title: 'Déconnexion de l\'Écosystème', box3Desc: 'Dès qu\'un échantillon est prélevé, sa structure se dégrade.', box4Title: 'Données Statiques vs. Flux Dynamique', box4Desc: 'Les tests ne fournissent qu\'un instantané.' },
  security: { watermark: 'SÉCURITÉ', tag: 'Bouclier Cyber', title: 'Données Immuables,', title2: 'Matériel Inaccessible.', desc: 'Vos données sont <strong>chiffrées de bout en bout</strong>.', card1Title: 'Protocole Match-Lock', card1Desc: 'L\'appareil est <strong>appairé cryptographiquement</strong> avec le compte utilisateur.', card1Badge: 'Mode Invisible Actif', card2Title: 'Code Génétique Numérique', card2Desc: 'Numéro de série <strong>unique de 30 chiffres</strong>.', card2Badge: 'Série 30 Chiffres', card3Title: 'BLOB SQL — Enregistrements Immuables', card3Desc: 'Liés par une <strong>chaîne de hachage cryptographique</strong>.', card3Badge: 'Vérifiable Rétroactivement' },
  vision: { tag: 'Rejoignez-nous', title: 'Transformer l\'Agriculture en un', title2: 'Écosystème Sans Humain et Sans Gaspillage.', desc1: 'Chez NaT, nous développons une solution autonome et pilotée par les données.', desc2: 'Nous invitons investisseurs, partenaires et pionniers à nous rejoindre.', cta: 'Contacter l\'Équipe Fondatrice' },
  footer: { ecosystem: 'Écosystème', company: 'Entreprise', legal: 'Juridique', home: 'Accueil', career: 'Carrière', contact: 'Contact', privacy: 'Politique de Confidentialité', kvkk: 'Protection des Données', terms: 'Conditions d\'Utilisation', copyright: '© 2026 NaT — Natural Agriculture Technologies. Tous droits réservés.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Envoyez-nous un message !', infoTag: 'Contact', infoTitleHtml: 'Sauvons<br/>le monde<br/><span class="highlight-text"><b>ensemble</b> !</span>', infoDesc: 'Nous sommes là pour toutes vos questions.', emailLabel: 'E-mail', coFounder: 'Co-Fondateur et Propriétaire', locationLabel: 'Emplacement', location: 'Turquie', formTitle: 'Envoyez Votre Message', nameField: 'Nom Complet', emailField: 'Adresse E-mail', nameError: 'Ce champ est obligatoire.', emailError: 'Veuillez entrer un e-mail valide.', orgToggleTitle: 'J\'écris au nom d\'une entreprise', orgToggleDesc: 'Partagez des détails supplémentaires.', orgNameField: 'Nom de l\'Entreprise', orgRoleField: 'Titre / Poste', subjectLabel: 'Sujet', subjectInvest: 'Investissement et Finance', subjectPartner: 'Partenariat Stratégique', subjectProduct: 'Produit et Technologie', subjectCareer: 'Carrière et Équipe', subjectMedia: 'Médias et Presse', subjectOther: 'Autre', subjectError: 'Veuillez sélectionner un sujet.', messageField: 'Votre Message', messageError: 'Le champ message est obligatoire.', submitBtn: 'Envoyer', submitting: 'Envoi en cours…', privacyNote: 'Vos informations sont en sécurité.', successMsg: 'Votre message a été envoyé avec succès !', errorMsg: 'Une erreur est survenue. Réessayez plus tard.', watermark: 'CONTACT' },
};
