import type { TranslationSet } from './types';
export const id: TranslationSet = {
  nav: { home: 'Beranda', problem: 'Masalah', hardware: 'Perangkat Keras', intelligence: 'Kecerdasan', operation: 'Operasional', security: 'Keamanan', join: 'Bergabung!', mobileToggle: 'Menu Seluler', mobileNav: 'Navigasi Seluler', mainNav: 'Navigasi Utama' },
  hero: { subtitle: 'Menghadapi krisis air dan pangan global, kami membangun ekosistem pertanian berbasis RAG yang sepenuhnya otonom, mampu mensimulasikan iklim mikro tersendiri untuk setiap tanaman.', exploreBtn: 'Jelajahi Visi Kami', pitchBtn: 'Unduh Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Krisis Global', title: 'Kami Tahu Masalahnya. Kami Membangun Solusinya.', desc: 'Pertanian global mendekati keruntuhan. Untuk memberi makan <strong>10 miliar orang pada tahun 2050</strong>, produksi harus ditingkatkan 60% — mustahil dengan metode saat ini.', card1Title: 'Bencana Diam: Pemborosan Air', card1Desc: '<strong>70%</strong> air tawar dunia digunakan di bidang pertanian, separuhnya hilang karena penguapan atau irigasi yang tidak tepat.', card2Title: 'Kerentanan terhadap Iklim', card2Desc: 'Pertanian konvensional sepenuhnya terekspos terhadap alam. Satu embun beku tak terduga dapat menghancurkan pekerjaan setahun dalam beberapa hari.', card3Title: 'Isolasi Data', card3Desc: 'Data pertanian tetap bersifat lokal dan terisolasi. Para petani mengulangi kesalahan yang sama tanpa mekanisme pembelajaran kolektif.' },
  coreVision: { tag: 'Desain Ekosistem', title: 'Untuk Setiap Tanaman, Di Mana Saja,\nSimulasi Iklim Mikro yang Sempurna.', desc: 'Tujuan NaT adalah sistem reaktif dan otonom yang tidak hanya membaca data — tetapi <strong>mengubah lingkungan</strong>.', feat1Title: 'Adaptasi Dinamis', feat1Desc: 'Terlepas dari lokasi lahan Anda, sistem membaca kebutuhan metabolisme tanaman secara instan.', feat2Title: 'Jaringan Suplai Presisi', feat2Desc: 'Menyediakan <strong>nutrisi, air, panas, dan pupuk</strong> dengan akurasi miligram, hanya saat dibutuhkan.', feat3Title: 'Mesin Pengambilan Keputusan Otonom', feat3Desc: 'Sebelum tanaman mengalami stres, sistem <strong>secara otomatis memicu</strong> intervensi mikro untuk menetralkan efek iklim.' },
  hardware: { watermark: 'PERANGKAT KERAS', tag: 'R&D Perangkat Keras', title: 'Kecerdasan Tertanam di Ladang: Seri sens', desc: 'Kami mengembangkan keluarga perangkat keras yang akan berfungsi sebagai ujung saraf ekosistem NaT.', sensTreeDesc: 'Perangkat IoT tangguh yang dipasang langsung di batang pohon untuk memantau proses biologis pohon.', sensSoilDesc: 'Sensor bawah tanah dengan desain tajam untuk penetrasi tanah yang mudah, mengukur NPK, pH, dan kelembaban.', sensPlantDesc: 'Perangkat pelacak klip untuk bibit, menganalisis perubahan biokimia untuk mendeteksi penyakit sebelum gejala muncul.' },
  rag: { watermark: 'KECERDASAN', tag: 'AI Berbasis RAG', title: 'Pengalaman Global, Tindakan Lokal.', desc: 'Tim kami membangun arsitektur RAG yang menggabungkan kekuatan LLM dengan basis data pertanian.', pred1Title: 'Prediksi Proaktif', pred1Desc: 'NaT dilatih untuk memproses data lapangan dan memprediksi: "Penyakit ini memiliki risiko 84% dalam 3 hari."', pred2Title: 'Pembelajaran Federasi Kolektif', pred2Desc: 'Setiap perangkat NaT melatih model pusat sambil menjaga privasi. Strategi dari Argentina diterapkan di Konya dalam hitungan detik.' },
  operation: { watermark: 'OPERASIONAL', tag: 'Visi Operasional', title: 'Transisi Otonom dari Diagnosis ke Pengobatan', desc: 'Pengumpulan data hanyalah setengah dari pekerjaan. Tujuan kami: mengubah data menjadi tindakan fisik yang otonom.', card1Title: 'Integrasi API dan Intervensi Bertarget', card1Desc: 'Ketika AI kami mengambil keputusan, ia mengirimkan perintah <strong>intervensi bertarget</strong> langsung ke drone atau sistem otonom.', card2Title: 'Hasil Maksimal, Bahan Kimia Minimal', card2Desc: 'Kami hanya menangani meter persegi yang terinfeksi — mengurangi penggunaan bahan kimia <strong>hingga 85%</strong>.' },
  lab: { title: 'Dalam 4 Langkah', subtitle: 'Melampaui Pengujian Laboratorium.', box1Title: 'Kehilangan Waktu dan Respons Tertunda', box1Desc: 'Pengujian laboratorium menyebabkan kerugian waktu yang besar. Pengambilan sampel dan hasil membutuhkan waktu berhari-hari.', box2Title: 'Kesalahan Pengambilan Sampel dan Keterwakilan', box2Desc: 'Segenggam tanah mewakili seluruh lahan. Namun struktur tanah tidak pernah homogen.', box3Title: 'Pemisahan Ekosistem', box3Desc: 'Tanah adalah ekosistem yang hidup. Segera setelah sampel diambil, dekomposisi mikrobiologis dimulai.', box4Title: 'Data Statis vs Aliran Dinamis', box4Desc: 'Pengujian laboratorium hanya memberikan snapshot sesaat. Pertanian adalah proses yang selalu dinamis.' },
  security: { watermark: 'KEAMANAN', tag: 'Perisai Siber', title: 'Data yang Tidak Dapat Diubah,', title2: 'Perangkat Keras yang Tidak Dapat Diakses.', desc: 'Ekosistem NaT dilindungi oleh enkripsi AES-256 tingkat militer. Data Anda <strong>dienkripsi secara end-to-end</strong>.', card1Title: 'Protokol Match-Lock', card1Desc: 'Saat terhubung, perangkat <strong>dipasangkan secara kriptografis</strong> dan beralih ke mode siluman.', card1Badge: 'Mode Siluman Aktif', card2Title: 'Kode Genetik Digital', card2Desc: 'Setiap perangkat disegel dengan nomor seri <strong>30 digit unik</strong>.', card2Badge: 'Nomor Seri 30 Digit', card3Title: 'BLOB SQL — Catatan Tidak Dapat Diubah', card3Desc: 'Semua catatan disimpan dalam format BLOB dan dihubungkan oleh <strong>rantai hash kriptografi</strong>.', card3Badge: 'Dapat Diverifikasi Retroaktif' },
  vision: { tag: 'Bergabung', title: 'Transformasi Pertanian Menjadi', title2: 'Ekosistem Tanpa Manusia dan Tanpa Limbah.', desc1: 'Di NaT, kami mengembangkan solusi berbasis data yang sepenuhnya otonom untuk krisis pertanian global. Visi kami: membebaskan pertanian dari ketergantungan.', desc2: 'Kami mengundang investor angel, mitra strategis, dan pelopor inovasi untuk bergabung bersama kami.', cta: 'Hubungi Tim Pendiri' },
  footer: { ecosystem: 'Ekosistem', company: 'Perusahaan', legal: 'Hukum', home: 'Beranda', career: 'Karir', contact: 'Kontak', privacy: 'Kebijakan Privasi', kvkk: 'Perlindungan Data', terms: 'Syarat Penggunaan', copyright: '© 2026 NaT — Natural Agriculture Technologies. Seluruh hak cipta dilindungi.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Kirim Pesan kepada Kami!', infoTag: 'Kontak', infoTitleHtml: 'Mari<br/>selamatkan<br/><span class="highlight-text"><b>dunia bersama</b>!</span>', infoDesc: 'Kami siap menjawab semua pertanyaan Anda tentang investasi, kolaborasi, karir, atau produk kami.', emailLabel: 'Email', coFounder: 'Co-Founder & Pemilik', locationLabel: 'Lokasi', location: 'Turki', formTitle: 'Kirim Pesan Anda', nameField: 'Nama Lengkap', emailField: 'Alamat Email', nameError: 'Bidang ini wajib diisi.', emailError: 'Silakan masukkan email yang valid.', orgToggleTitle: 'Saya menulis atas nama perusahaan atau organisasi', orgToggleDesc: 'Bagikan detail tambahan untuk pesan korporat.', orgNameField: 'Perusahaan / Organisasi', orgRoleField: 'Jabatan / Posisi', subjectLabel: 'Subjek', subjectInvest: 'Investasi & Keuangan', subjectPartner: 'Kemitraan Strategis', subjectProduct: 'Produk & Teknologi', subjectCareer: 'Karir & Tim', subjectMedia: 'Media & Pers', subjectOther: 'Lainnya', subjectError: 'Silakan pilih subjek.', messageField: 'Pesan Anda', messageError: 'Bidang pesan wajib diisi.', submitBtn: 'Kirim', submitting: 'Mengirim…', privacyNote: 'Informasi Anda aman dan tidak akan dibagikan kepada pihak ketiga.', successMsg: 'Pesan Anda berhasil dikirim!', errorMsg: 'Terjadi kesalahan. Silakan coba lagi nanti.', watermark: 'KONTAK' },
};
