import type { TranslationSet } from './types';
export const it: TranslationSet = {
  nav: { home: 'Home', problem: 'Problema', hardware: 'Hardware', intelligence: 'Intelligenza', operation: 'Operazione', security: 'Sicurezza', join: 'Unisciti!', mobileToggle: 'Menu mobile', mobileNav: 'Navigazione mobile', mainNav: 'Navigazione principale' },
  hero: { subtitle: 'Contro la crisi globale dell\'acqua e del cibo, stiamo costruendo un ecosistema agricolo completamente autonomo basato su RAG.', exploreBtn: 'Scopri la Nostra Visione', pitchBtn: 'Scarica Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Crisi Globale', title: 'Conosciamo il Problema. Stiamo Costruendo la Soluzione.', desc: 'L\'agricoltura globale si avvicina al collasso. Per sfamare <strong>10 miliardi di persone entro il 2050</strong>, dobbiamo aumentare la produzione del 60%.', card1Title: 'Catastrofe Silenziosa: Spreco d\'Acqua', card1Desc: 'Il <strong>70%</strong> dell\'acqua dolce è usata in agricoltura e metà si perde.', card2Title: 'Vulnerabilità Climatica', card2Desc: 'L\'agricoltura convenzionale è in balia della natura.', card3Title: 'Isolamento dei Dati', card3Desc: 'I dati agricoli restano locali e isolati.' },
  coreVision: { tag: 'Design dell\'Ecosistema', title: 'Simulazione Perfetta del Microclima\nper Ogni Pianta, Ovunque.', desc: 'In NaT, creiamo un sistema che <strong>cambia l\'ambiente</strong>.', feat1Title: 'Adattamento Dinamico', feat1Desc: 'Il sistema legge i bisogni metabolici immediati delle piante.', feat2Title: 'Rete di Integrazione Precisa', feat2Desc: 'Fornisce <strong>nutrienti, acqua, calore e fertilizzante</strong> con precisione.', feat3Title: 'Motore Decisionale Autonomo', feat3Desc: '<strong>Attiva automaticamente</strong> micro-interventi.' },
  hardware: { watermark: 'HARDWARE', tag: 'R&S Hardware', title: 'Intelligenza Integrata nel Campo: sensSeries', desc: 'Stiamo progettando la famiglia hardware del ecosistema NaT.', sensTreeDesc: 'Un dispositivo IoT robusto montato sul tronco.', sensSoilDesc: 'Un sensore sotterraneo per la penetrazione del suolo.', sensPlantDesc: 'Un dispositivo a clip per le piantine.' },
  rag: { watermark: 'INTELLIGENZA', tag: 'IA Basata su RAG', title: 'Esperienza Globale, Azione Locale.', desc: 'Il nostro team costruisce un\'architettura RAG con LLM e database agricoli.', pred1Title: 'Previsione Proattiva', pred1Desc: 'NaT prevede: "questa malattia ha un rischio dell\'84% in 3 giorni."', pred2Title: 'Apprendimento Federato Collettivo', pred2Desc: 'Ogni dispositivo addestra il modello centrale preservando la privacy.' },
  operation: { watermark: 'OPERAZIONE', tag: 'Visione Operativa', title: 'Transizione Autonoma dalla Diagnosi al Trattamento', desc: 'Il nostro vero obiettivo: trasformare i dati in azione fisica autonoma.', card1Title: 'Integrazione API e Intervento Mirato', card1Desc: 'La nostra IA invia comandi di <strong>intervento mirato</strong> ai droni.', card2Title: 'Massima Resa, Minima Chimica', card2Desc: 'Riduzione dell\'uso di sostanze chimiche <strong>fino all\'85%</strong>.' },
  lab: { title: 'In 4 Passaggi', subtitle: 'Superiamo i test di laboratorio.', box1Title: 'Perdita di Tempo', box1Desc: 'Il campionamento e i risultati richiedono giorni.', box2Title: 'Errore di Campionamento', box2Desc: 'Poche manciate di terra rappresentano un campo intero.', box3Title: 'Disconnessione dall\'Ecosistema', box3Desc: 'Appena un campione viene prelevato, si degrada.', box4Title: 'Dati Statici vs. Flusso Dinamico', box4Desc: 'I test forniscono solo un\'istantanea.' },
  security: { watermark: 'SICUREZZA', tag: 'Scudo Cyber', title: 'Dati Immutabili,', title2: 'Hardware Inaccessibile.', desc: 'I vostri dati sono <strong>crittografati end-to-end</strong>.', card1Title: 'Protocollo Match-Lock', card1Desc: 'Il dispositivo è <strong>accoppiato crittograficamente</strong>.', card1Badge: 'Modalità Invisibile Attiva', card2Title: 'Codice Genetico Digitale', card2Desc: 'Numero di serie <strong>unico di 30 cifre</strong>.', card2Badge: 'Serie 30 Cifre', card3Title: 'BLOB SQL — Registri Immutabili', card3Desc: 'Collegati da una <strong>catena hash crittografica</strong>.', card3Badge: 'Verificabile Retroattivamente' },
  vision: { tag: 'Unisciti a Noi', title: 'Trasformare l\'Agricoltura in un', title2: 'Ecosistema Senza Umani e Senza Sprechi.', desc1: 'In NaT, sviluppiamo una soluzione autonoma e basata sui dati.', desc2: 'Invitiamo angel investor, partner strategici e pionieri a unirsi.', cta: 'Contatta il Team Fondatore' },
  footer: { ecosystem: 'Ecosistema', company: 'Azienda', legal: 'Legale', home: 'Home', career: 'Carriera', contact: 'Contatto', privacy: 'Informativa sulla Privacy', kvkk: 'Protezione dei Dati', terms: 'Termini di Utilizzo', copyright: '© 2026 NaT — Natural Agriculture Technologies. Tutti i diritti riservati.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Inviaci un messaggio!', infoTag: 'Contatto', infoTitleHtml: 'Salviamo<br/>il mondo<br/><span class="highlight-text"><b>insieme</b>!</span>', infoDesc: 'Siamo qui per tutte le vostre domande.', emailLabel: 'E-mail', coFounder: 'Co-Fondatore e Proprietario', locationLabel: 'Posizione', location: 'Turchia', formTitle: 'Invia il Tuo Messaggio', nameField: 'Nome Completo', emailField: 'Indirizzo E-mail', nameError: 'Campo obbligatorio.', emailError: 'Inserisci un\'e-mail valida.', orgToggleTitle: 'Scrivo per conto di un\'azienda', orgToggleDesc: 'Condividi dettagli aggiuntivi.', orgNameField: 'Nome Azienda', orgRoleField: 'Titolo / Posizione', subjectLabel: 'Oggetto', subjectInvest: 'Investimenti e Finanza', subjectPartner: 'Partnership Strategica', subjectProduct: 'Prodotto e Tecnologia', subjectCareer: 'Carriera e Team', subjectMedia: 'Media e Stampa', subjectOther: 'Altro', subjectError: 'Seleziona un oggetto.', messageField: 'Il Tuo Messaggio', messageError: 'Il campo messaggio è obbligatorio.', submitBtn: 'Invia', submitting: 'Invio in corso…', privacyNote: 'Le tue informazioni sono al sicuro.', successMsg: 'Messaggio inviato con successo!', errorMsg: 'Errore. Riprova più tardi.', watermark: 'CONTATTO' },
};
