import type { TranslationSet } from './types';
export const ja: TranslationSet = {
  nav: { home: 'ホーム', problem: '課題', hardware: 'ハードウェア', intelligence: 'インテリジェンス', operation: '運用', security: 'セキュリティ', join: '参加する！', mobileToggle: 'モバイルメニュー', mobileNav: 'モバイルナビゲーション', mainNav: 'メインナビゲーション' },
  hero: { subtitle: '世界的な水・食料危機に対し、私たちはすべての植物に独自のマイクロ気候をシミュレートできる、完全自律型のRAGベース農業エコシステムを構築しています。', exploreBtn: 'ビジョンを探る', pitchBtn: 'ピッチデッキをダウンロード', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'グローバル危機', title: '問題は分かっている。解決策を構築している。', desc: '世界農業は崩壊に向かっています。<strong>2050年までに100億人</strong>を養うには、現在の方法では不可能な60%の生産増加が必要です。', card1Title: '静かな災害：水の無駄遣い', card1Desc: '世界の淡水の<strong>70%</strong>が農業で使用されており、その半分が蒸発や誤った灌漑によって失われています。', card2Title: '気候への脆弱性', card2Desc: '従来農業は自然の気まぐれに左右されます。予期せぬ霜が数日で一年分の作業を壊滅させる可能性があります。', card3Title: 'データの孤立', card3Desc: '農業データはローカルかつ孤立したままです。農家は集合的な学習メカニズムなしに同じ過ちを繰り返しています。' },
  coreVision: { tag: 'エコシステム設計', title: 'あらゆる植物に、どこでも、\n完璧なマイクロ気候シミュレーション。', desc: 'NaTの目標は、データを読み取るだけでなく—<strong>環境を変える</strong>—反応的で自律的なシステムです。', feat1Title: 'ダイナミックな適応', feat1Desc: '圃場の場所に関係なく、システムは植物の即時の代謝ニーズを読み取ります。', feat2Title: '精密補給ネットワーク', feat2Desc: '必要なときだけ、ミリグラム精度で<strong>栄養素、水、熱、肥料</strong>を供給します。', feat3Title: '自律的意思決定エンジン', feat3Desc: '植物がストレスを受ける前に、気候の影響を中和するマイクロ介入を<strong>自動的にトリガー</strong>します。' },
  hardware: { watermark: 'ハードウェア', tag: 'ハードウェアR&D', title: '圃場に組み込まれたインテリジェンス：sensシリーズ', desc: 'NaTエコシステムの神経末端として機能するハードウェアファミリーを開発しています。', sensTreeDesc: '幹に直接取り付けられ、樹木の生物学的プロセスを監視する堅牢なIoTデバイス。', sensSoilDesc: '土壌侵入が容易なシャープなデザインの地中センサーで、NPK、pH、水分を計測。', sensPlantDesc: '症状が現れる前に疾患を検出するため、生化学的変化を分析する苗木用クリップ追跡デバイス。' },
  rag: { watermark: 'インテリジェンス', tag: 'RAGベースAI', title: 'グローバルな経験、ローカルな行動。', desc: '私たちのチームはLLMの力と農業データベースを組み合わせたRAGアーキテクチャを構築しています。', pred1Title: '予防的予測', pred1Desc: 'NaTはフィールドデータを処理し「この病気は3日後に84%のリスクがある」と予測するよう訓練されます。', pred2Title: '集合的連合学習', pred2Desc: 'すべてのNaTデバイスはプライバシーを保護しながら中央モデルを訓練します。アルゼンチンからの戦略がコンヤで数秒以内に適用されます。' },
  operation: { watermark: '運用', tag: '運用ビジョン', title: '診断から治療への自律的移行', desc: 'データ収集は作業の半分に過ぎません。私たちの目標：データを自律的な物理的行動に変換することです。', card1Title: 'API統合と標的介入', card1Desc: 'AIが判断すると、ドローンや自律システムに直接<strong>標的介入</strong>コマンドを送信します。', card2Title: '最大収量、最小化学物質', card2Desc: '病気になった特定の平方メートルのみを処置し、化学物質の使用を<strong>最大85%</strong>削減します。' },
  lab: { title: '4つのステップで', subtitle: 'ラボテストを超える。', box1Title: '時間のロスと遅延反応', box1Desc: 'ラボテストは膨大な時間のロスを招きます。サンプリングと結果には数日かかります。', box2Title: 'サンプリングエラーと代表性', box2Desc: 'ほんの一握りの土が畑全体を代表します。しかし土壌構造は均一ではありません。', box3Title: 'エコシステムの分離', box3Desc: '土壌は生きたエコシステムです。サンプルを採取した瞬間から微生物分解が始まります。', box4Title: '静的データ対動的フロー', box4Desc: 'ラボテストは瞬間のスナップショットのみを提供します。農業は常に動的なプロセスです。' },
  security: { watermark: 'セキュリティ', tag: 'サイバーシールド', title: '不変のデータ、', title2: 'アクセス不能なハードウェア。', desc: 'NaTエコシステムは軍事レベルのAES-256暗号化で保護されています。あなたのデータは<strong>エンドツーエンドで暗号化</strong>されています。', card1Title: 'マッチロックプロトコル', card1Desc: '接続時にデバイスは<strong>暗号学的にペアリング</strong>され、ステルスモードに切り替わります。', card1Badge: 'ステルスモード有効', card2Title: 'デジタル遺伝子コード', card2Desc: '各デバイスは<strong>固有の30桁</strong>のシリアル番号で封印されています。', card2Badge: '30桁シリアル番号', card3Title: 'BLOB SQL — 不変の記録', card3Desc: 'すべての記録はBLOB形式で保存され、<strong>暗号学的ハッシュチェーン</strong>で連結されています。', card3Badge: '遡及的に検証可能' },
  vision: { tag: '参加する', title: '農業を変革する', title2: '人手不要・廃棄物ゼロのエコシステムへ。', desc1: 'NaTでは、世界的農業危機に対するデータ駆動型の完全自律ソリューションを開発しています。私たちのビジョン：農業を依存から解放すること。', desc2: 'エンジェル投資家、戦略的パートナー、イノベーションのパイオニアの方々をお招きしています。', cta: '創業チームに連絡する' },
  footer: { ecosystem: 'エコシステム', company: '会社', legal: '法律', home: 'ホーム', career: 'キャリア', contact: 'お問い合わせ', privacy: 'プライバシーポリシー', kvkk: 'データ保護', terms: '利用規約', copyright: '© 2026 NaT — Natural Agriculture Technologies. 全著作権所有。' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'メッセージを送る！', infoTag: 'お問い合わせ', infoTitleHtml: '一緒に<br/>世界を<br/><span class="highlight-text"><b>救おう</b>！</span>', infoDesc: '投資、協業、キャリア、製品に関するご質問にお答えします。', emailLabel: 'メール', coFounder: '共同創業者 & オーナー', locationLabel: '所在地', location: 'トルコ', formTitle: 'メッセージを送信', nameField: '氏名', emailField: 'メールアドレス', nameError: 'このフィールドは必須です。', emailError: '有効なメールアドレスを入力してください。', orgToggleTitle: '企業または組織の代表として連絡しています', orgToggleDesc: '法人メッセージの追加詳細を共有してください。', orgNameField: '会社 / 組織', orgRoleField: '役職 / ポジション', subjectLabel: '件名', subjectInvest: '投資 & ファイナンス', subjectPartner: '戦略的パートナーシップ', subjectProduct: '製品 & テクノロジー', subjectCareer: 'キャリア & チーム', subjectMedia: 'メディア & プレス', subjectOther: 'その他', subjectError: '件名を選択してください。', messageField: 'メッセージ', messageError: 'メッセージフィールドは必須です。', submitBtn: '送信', submitting: '送信中…', privacyNote: 'お客様の情報は安全に保護され、第三者に共有されません。', successMsg: 'メッセージが正常に送信されました！', errorMsg: 'エラーが発生しました。後ほど再試行してください。', watermark: 'お問い合わせ' },
};
