import type { TranslationSet } from './types';
export const ko: TranslationSet = {
  nav: { home: '홈', problem: '문제', hardware: '하드웨어', intelligence: '인텔리전스', operation: '운용', security: '보안', join: '참여하기!', mobileToggle: '모바일 메뉴', mobileNav: '모바일 내비게이션', mainNav: '메인 내비게이션' },
  hero: { subtitle: '세계적인 물·식량 위기에 맞서, 우리는 모든 식물에 자체 미기후를 시뮬레이션할 수 있는 완전 자율형 RAG 기반 농업 생태계를 구축하고 있습니다.', exploreBtn: '비전 탐색하기', pitchBtn: '피치덱 다운로드', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: '글로벌 위기', title: '우리는 문제를 안다. 우리는 해결책을 구축하고 있다.', desc: '세계 농업은 붕괴에 가까워지고 있습니다. <strong>2050년까지 100억 명</strong>을 먹이기 위해서는 생산량을 60% 늘려야 하지만, 현재의 방법으로는 불가능합니다.', card1Title: '조용한 재앙: 물 낭비', card1Desc: '세계 담수의 <strong>70%</strong>가 농업에 사용되며, 그 절반은 증발이나 잘못된 관개로 손실됩니다.', card2Title: '기후 취약성', card2Desc: '기존 농업은 자연에 노출되어 있습니다. 예상치 못한 서리 한 번으로 1년간의 작업이 며칠 만에 파괴될 수 있습니다.', card3Title: '데이터 고립', card3Desc: '농업 데이터는 로컬에 고립된 채로 남아 있습니다. 농부들은 집단적 학습 메커니즘 없이 같은 실수를 반복합니다.' },
  coreVision: { tag: '생태계 설계', title: '모든 식물에, 어디서나,\n완벽한 미기후 시뮬레이션。', desc: 'NaT의 목표는 데이터를 읽는 것에 그치지 않고—<strong>환경을 바꾸는</strong>—반응적이고 자율적인 시스템입니다.', feat1Title: '동적 적응', feat1Desc: '경작지 위치에 관계없이 시스템이 식물의 즉각적인 대사 요구를 읽어냅니다.', feat2Title: '정밀 보충 네트워크', feat2Desc: '필요할 때만 밀리그램 정밀도로 <strong>영양소, 물, 열, 비료</strong>를 공급합니다.', feat3Title: '자율 의사결정 엔진', feat3Desc: '식물이 스트레스를 받기 전에 기후 영향을 중화하는 미세 개입을 <strong>자동으로 트리거</strong>합니다。' },
  hardware: { watermark: '하드웨어', tag: '하드웨어 R&D', title: '농지에 내장된 인텔리전스: sens시리즈', desc: 'NaT 생태계의 신경 말단 역할을 할 하드웨어 패밀리를 개발하고 있습니다.', sensTreeDesc: '나무의 생물학적 과정을 모니터링하기 위해 줄기에 직접 장착되는 견고한 IoT 기기.', sensSoilDesc: '쉬운 토양 침투를 위한 예리한 디자인의 지하 센서로 NPK, pH, 수분을 측정합니다.', sensPlantDesc: '증상이 나타나기 전에 질병을 감지하기 위해 생화학적 변화를 분석하는 묘목용 클립 추적 기기.' },
  rag: { watermark: '인텔리전스', tag: 'RAG 기반 AI', title: '글로벌 경험, 로컬 행동.', desc: '우리 팀은 LLM의 힘과 농업 데이터베이스를 결합한 RAG 아키텍처를 구축하고 있습니다.', pred1Title: '선제적 예측', pred1Desc: 'NaT는 현장 데이터를 처리하여 "이 질병은 3일 후 84%의 위험이 있다"고 예측하도록 훈련됩니다.', pred2Title: '집합적 연합 학습', pred2Desc: '모든 NaT 기기는 개인정보를 보호하면서 중앙 모델을 훈련합니다. 아르헨티나의 전략이 코냐에서 수 초 내에 적용됩니다.' },
  operation: { watermark: '운용', tag: '운용 비전', title: '진단에서 치료까지 자율적 전환', desc: '데이터 수집은 작업의 절반에 불과합니다. 우리의 목표: 데이터를 자율적인 물리적 행동으로 변환하는 것입니다.', card1Title: 'API 통합과 표적 개입', card1Desc: 'AI가 결정하면 드론이나 자율 시스템에 직접 <strong>표적 개입</strong> 명령을 전송합니다.', card2Title: '최대 수확량, 최소 화학물질', card2Desc: '병든 특정 평방미터만 처리하여 화학물질 사용을 <strong>최대 85%</strong> 줄입니다.' },
  lab: { title: '4단계로', subtitle: '실험실 테스트를 넘어서다.', box1Title: '시간 손실과 지연된 반응', box1Desc: '실험실 테스트는 엄청난 시간 손실을 초래합니다. 샘플링과 결과에 며칠이 걸립니다.', box2Title: '샘플링 오류와 대표성', box2Desc: '한 줌의 흙이 전체 농지를 대표합니다. 그러나 토양 구조는 결코 균일하지 않습니다.', box3Title: '생태계 분리', box3Desc: '토양은 살아있는 생태계입니다. 샘플을 채취하는 순간 미생물 분해가 시작됩니다.', box4Title: '정적 데이터 대 동적 흐름', box4Desc: '실험실 테스트는 순간의 스냅샷만 제공합니다. 농업은 항상 동적인 과정입니다.' },
  security: { watermark: '보안', tag: '사이버 쉴드', title: '불변의 데이터,', title2: '접근 불가능한 하드웨어.', desc: 'NaT 생태계는 군사급 AES-256 암호화로 보호됩니다. 귀하의 데이터는 <strong>엔드투엔드 암호화</strong>되어 있습니다.', card1Title: '매치락 프로토콜', card1Desc: '연결 시 기기는 <strong>암호학적으로 페어링</strong>되고 스텔스 모드로 전환됩니다.', card1Badge: '스텔스 모드 활성', card2Title: '디지털 유전자 코드', card2Desc: '각 기기는 <strong>고유한 30자리</strong> 일련번호로 봉인됩니다.', card2Badge: '30자리 일련번호', card3Title: 'BLOB SQL — 불변 기록', card3Desc: '모든 기록은 BLOB 형식으로 저장되고 <strong>암호학적 해시 체인</strong>으로 연결됩니다.', card3Badge: '소급 검증 가능' },
  vision: { tag: '참여하기', title: '농업을 변환하다', title2: '무인·무폐기물 생태계로.', desc1: 'NaT에서는 세계적 농업 위기에 대한 데이터 기반의 완전 자율 솔루션을 개발하고 있습니다. 우리의 비전: 농업을 의존에서 해방시키는 것.', desc2: '엔젤 투자자, 전략적 파트너, 혁신의 개척자들을 초대합니다.', cta: '창업팀에 연락하기' },
  footer: { ecosystem: '생태계', company: '회사', legal: '법률', home: '홈', career: '커리어', contact: '문의', privacy: '개인정보처리방침', kvkk: '데이터 보호', terms: '이용약관', copyright: '© 2026 NaT — Natural Agriculture Technologies. 모든 권리 보유.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: '메시지를 보내세요!', infoTag: '연락처', infoTitleHtml: '함께<br/>세상을<br/><span class="highlight-text"><b>구하자</b>!</span>', infoDesc: '투자, 협업, 커리어, 제품에 관한 모든 질문에 답변드립니다.', emailLabel: '이메일', coFounder: '공동 창업자 & 오너', locationLabel: '위치', location: '튀르키예', formTitle: '메시지 보내기', nameField: '성명', emailField: '이메일 주소', nameError: '이 항목은 필수입니다.', emailError: '유효한 이메일 주소를 입력해주세요.', orgToggleTitle: '기업 또는 조직을 대표하여 연락합니다', orgToggleDesc: '법인 메시지를 위한 추가 정보를 공유해주세요.', orgNameField: '회사 / 조직', orgRoleField: '직함 / 직위', subjectLabel: '제목', subjectInvest: '투자 & 재무', subjectPartner: '전략적 파트너십', subjectProduct: '제품 & 기술', subjectCareer: '커리어 & 팀', subjectMedia: '미디어 & 언론', subjectOther: '기타', subjectError: '제목을 선택해주세요.', messageField: '메시지', messageError: '메시지 항목은 필수입니다.', submitBtn: '전송', submitting: '전송 중…', privacyNote: '귀하의 정보는 안전하게 보호되며 제3자와 공유되지 않습니다.', successMsg: '메시지가 성공적으로 전송되었습니다!', errorMsg: '오류가 발생했습니다. 나중에 다시 시도해주세요.', watermark: '연락처' },
};
