import type { TranslationSet } from './types';
export const nl: TranslationSet = {
  nav: { home: 'Home', problem: 'Probleem', hardware: 'Hardware', intelligence: 'Intelligentie', operation: 'Operatie', security: 'Beveiliging', join: 'Doe Mee!', mobileToggle: 'Mobiel menu', mobileNav: 'Mobiele navigatie', mainNav: 'Hoofdnavigatie' },
  hero: { subtitle: 'Tegen de wereldwijde water- en voedselcrisis bouwen wij een volledig autonoom, RAG-gebaseerd landbouwecosysteem.', exploreBtn: 'Ontdek Onze Visie', pitchBtn: 'Download Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Wereldwijde Crisis', title: 'We Kennen het Probleem. We Bouwen de Oplossing.', desc: 'De wereldlandbouw nadert ineenstorting. Om <strong>10 miljard mensen in 2050</strong> te voeden, moeten we de productie met 60% verhogen.', card1Title: 'Stille Catastrofe: Waterverspilling', card1Desc: '<strong>70%</strong> van het zoetwater wordt gebruikt in de landbouw.', card2Title: 'Klimaatwetsbaarheid', card2Desc: 'Conventionele landbouw is overgeleverd aan de natuur.', card3Title: 'Data-isolatie', card3Desc: 'Landbouwgegevens blijven lokaal en geïsoleerd.' },
  coreVision: { tag: 'Ecosysteem Ontwerp', title: 'Perfecte Microklimaat-simulatie\nvoor Elke Plant, Overal.', desc: 'Bij NaT is ons doel een systeem dat de <strong>omgeving verandert</strong>.', feat1Title: 'Dynamische Aanpassing', feat1Desc: 'Het systeem leest de metabolische behoeften van de planten.', feat2Title: 'Precies Aanvullingsnetwerk', feat2Desc: 'Levert <strong>voedingsstoffen, water, warmte en meststof</strong> met precisie.', feat3Title: 'Autonome Beslissingsmotor', feat3Desc: '<strong>Activeert automatisch</strong> micro-interventies.' },
  hardware: { watermark: 'HARDWARE', tag: 'Hardware R&D', title: 'Intelligentie in het Veld: sensSeries', desc: 'We ontwerpen de hardwarefamilie van het NaT-ecosysteem.', sensTreeDesc: 'Een robuust IoT-apparaat op de stam.', sensSoilDesc: 'Een ondergrondse sensor voor bodempenetratie.', sensPlantDesc: 'Een clip-trackingapparaat voor zaailingen.' },
  rag: { watermark: 'INTELLIGENTIE', tag: 'RAG-gebaseerde AI', title: 'Wereldwijde Ervaring, Lokale Actie.', desc: 'Ons team bouwt een RAG-architectuur met LLM\'s en landbouwdatabases.', pred1Title: 'Proactieve Voorspelling', pred1Desc: 'NaT voorspelt: "deze ziekte heeft 84% risico over 3 dagen."', pred2Title: 'Collectief Federatief Leren', pred2Desc: 'Elk apparaat traint het centrale model met behoud van privacy.' },
  operation: { watermark: 'OPERATIE', tag: 'Operationele Visie', title: 'Autonome Overgang van Diagnose naar Behandeling', desc: 'Ons doel: data omzetten in autonome fysieke actie.', card1Title: 'API-integratie en Gerichte Interventie', card1Desc: 'Onze AI stuurt <strong>gerichte interventie</strong>-opdrachten naar drones.', card2Title: 'Maximale Opbrengst, Minimale Chemie', card2Desc: 'Chemicaliëngebruik <strong>tot 85%</strong> verminderd.' },
  lab: { title: 'In 4 Stappen', subtitle: 'Wij overtreffen laboratoriumtests.', box1Title: 'Tijdverlies', box1Desc: 'Monstername en resultaten duren dagen.', box2Title: 'Steekproeffout', box2Desc: 'Een handvol grond vertegenwoordigt een heel veld.', box3Title: 'Ecosysteem Ontkoppeling', box3Desc: 'Bij monstername begint microbiologische afbraak.', box4Title: 'Statische Data vs. Dynamische Stroom', box4Desc: 'Labtests geven slechts een momentopname.' },
  security: { watermark: 'BEVEILIGING', tag: 'Cyberschild', title: 'Onveranderlijke Data,', title2: 'Ontoegankelijke Hardware.', desc: 'Uw gegevens zijn <strong>end-to-end versleuteld</strong>.', card1Title: 'Match-Lock Protocol', card1Desc: 'Het apparaat wordt <strong>cryptografisch gekoppeld</strong>.', card1Badge: 'Stealth-modus Actief', card2Title: 'Digitale Genetische Code', card2Desc: '<strong>Uniek 30-cijferig</strong> serienummer.', card2Badge: '30-Cijferig Serienummer', card3Title: 'BLOB SQL — Onveranderlijke Records', card3Desc: 'Gekoppeld met een <strong>cryptografische hashketen</strong>.', card3Badge: 'Achteraf Verifieerbaar' },
  vision: { tag: 'Doe Mee', title: 'Landbouw Transformeren naar een', title2: 'Mensloos, Verspillingsvrij Ecosysteem.', desc1: 'Bij NaT ontwikkelen we een datagestuurde, volledig autonome oplossing.', desc2: 'Wij nodigen investeerders, partners en innovatiepioniers uit.', cta: 'Neem Contact op met het Oprichtersteam' },
  footer: { ecosystem: 'Ecosysteem', company: 'Bedrijf', legal: 'Juridisch', home: 'Home', career: 'Carrière', contact: 'Contact', privacy: 'Privacybeleid', kvkk: 'Gegevensbescherming', terms: 'Gebruiksvoorwaarden', copyright: '© 2026 NaT — Natural Agriculture Technologies. Alle rechten voorbehouden.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Stuur ons een bericht!', infoTag: 'Contact', infoTitleHtml: 'Red de<br/>wereld<br/><span class="highlight-text"><b>samen</b>!</span>', infoDesc: 'Wij staan klaar voor al uw vragen.', emailLabel: 'E-mail', coFounder: 'Medeoprichter & Eigenaar', locationLabel: 'Locatie', location: 'Turkije', formTitle: 'Stuur Uw Bericht', nameField: 'Volledige Naam', emailField: 'E-mailadres', nameError: 'Dit veld is verplicht.', emailError: 'Voer een geldig e-mail in.', orgToggleTitle: 'Ik schrijf namens een bedrijf', orgToggleDesc: 'Deel aanvullende informatie.', orgNameField: 'Bedrijf / Organisatie', orgRoleField: 'Titel / Functie', subjectLabel: 'Onderwerp', subjectInvest: 'Investering & Financiën', subjectPartner: 'Strategisch Partnerschap', subjectProduct: 'Product & Technologie', subjectCareer: 'Carrière & Team', subjectMedia: 'Media & Pers', subjectOther: 'Overig', subjectError: 'Selecteer een onderwerp.', messageField: 'Uw Bericht', messageError: 'Berichtveld is verplicht.', submitBtn: 'Verzenden', submitting: 'Verzenden…', privacyNote: 'Uw informatie is veilig.', successMsg: 'Uw bericht is succesvol verzonden!', errorMsg: 'Er is een fout opgetreden. Probeer het later opnieuw.', watermark: 'CONTACT' },
};
