import type { TranslationSet } from './types';
export const nl: TranslationSet = {
  nav: { home: 'Home', problem: 'Probleem', hardware: 'Hardware', intelligence: 'Intelligentie', operation: 'Operatie', security: 'Beveiliging', join: 'Doe Mee!', mobileToggle: 'Mobiel menu', mobileNav: 'Mobiele navigatie', mainNav: 'Hoofdnavigatie' },
  hero: { subtitle: 'Tegen de wereldwijde water- en voedselcrisis bouwen wij een volledig autonoom, RAG-gebaseerd landbouwecosysteem dat zijn eigen microklimaat kan simuleren voor elke plant.', exploreBtn: 'Ontdek Onze Visie', pitchBtn: 'Download Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Wereldwijde Crisis', title: 'We Kennen het Probleem. We Bouwen de Oplossing.', desc: 'De wereldlandbouw nadert een ineenstorting. Om <strong>10 miljard mensen in 2050</strong> te voeden, moeten we de productie met 60% verhogen — onmogelijk met huidige methoden.', card1Title: 'Stille Catastrofe: Waterverspilling', card1Desc: '<strong>70%</strong> van het zoetwater wordt gebruikt in de landbouw en de helft gaat verloren door verdamping of verkeerde irrigatie.', card2Title: 'Klimaatwetsbaarheid', card2Desc: 'Conventionele landbouw is overgeleverd aan de natuur. Onverwachte vorst kan het werk van een jaar in dagen vernietigen.', card3Title: 'Data-isolatie', card3Desc: 'Landbouwgegevens blijven lokaal en geïsoleerd. Boeren herhalen dezelfde fouten zonder collectief leermechanisme.' },
  coreVision: { tag: 'Ecosysteem Ontwerp', title: 'Perfecte Microklimaat-simulatie\nvoor Elke Plant, Overal.', desc: 'Bij NaT is ons doel een reactief en autonoom systeem dat niet alleen data leest — het <strong>verandert de omgeving</strong>.', feat1Title: 'Dynamische Aanpassing', feat1Desc: 'Ongeacht de locatie van uw veld, het systeem leest de directe metabolische behoeften van de planten.', feat2Title: 'Precies Aanvullingsnetwerk', feat2Desc: 'Levert <strong>voedingsstoffen, water, warmte en meststof</strong> met milligram-precisie, alleen wanneer nodig.', feat3Title: 'Autonome Beslissingsmotor', feat3Desc: 'Voordat de plant stress ervaart, <strong>activeert het automatisch</strong> micro-interventies om klimaateffecten te neutraliseren.' },
  hardware: { watermark: 'HARDWARE', tag: 'Hardware R&D', title: 'Intelligentie in het Veld: sensSeries', desc: 'We ontwerpen de hardwarefamilie die als zenuwuiteinden van het NaT-ecosysteem zal dienen.', sensTreeDesc: 'Een robuust IoT-apparaat dat direct op de stam wordt gemonteerd om biologische processen van bomen te monitoren.', sensSoilDesc: 'Een ondergrondse sensor met scherp ontwerp voor eenvoudige bodemendoordinging, meet NPK, pH en vocht.', sensPlantDesc: 'Een clip-trackingapparaat voor zaailingen dat biochemische veranderingen analyseert om ziekten te detecteren vóór symptomen.' },
  rag: { watermark: 'INTELLIGENTIE', tag: 'RAG-gebaseerde AI', title: 'Wereldwijde Ervaring, Lokale Actie.', desc: 'Ons team bouwt een RAG-architectuur die de kracht van LLM\'s combineert met landbouwdatabases.', pred1Title: 'Proactieve Voorspelling', pred1Desc: 'NaT wordt getraind om veldgegevens te verwerken en te voorspellen: "deze ziekte heeft 84% risico over 3 dagen."', pred2Title: 'Collectief Federatief Leren', pred2Desc: 'Elk NaT-apparaat traint het centrale model met behoud van privacy. Een strategie uit Argentinië wordt in Konya in seconden toegepast.' },
  operation: { watermark: 'OPERATIE', tag: 'Operationele Visie', title: 'Autonome Overgang van Diagnose naar Behandeling', desc: 'Data verzamelen is slechts de helft. Ons doel: data omzetten in autonome fysieke actie.', card1Title: 'API-integratie en Gerichte Interventie', card1Desc: 'Wanneer onze AI beslist, stuurt het <strong>gerichte interventie</strong>-opdrachten direct naar drones of autonome systemen.', card2Title: 'Maximale Opbrengst, Minimale Chemie', card2Desc: 'We behandelen alleen de specifieke vierkante meters, waardoor chemicaliëngebruik <strong>tot 85%</strong> vermindert.' },
  lab: { title: 'In 4 Stappen', subtitle: 'Wij overtreffen laboratoriumtests.', box1Title: 'Tijdverlies en Vertraagde Reactie', box1Desc: 'Labtests veroorzaken enorm tijdverlies. Monstername en resultaten duren dagen.', box2Title: 'Steekproeffout en Representatie', box2Desc: 'Slechts een handvol grond vertegenwoordigt een heel veld. Maar bodemstructuur is nooit homogeen.', box3Title: 'Ecosysteem Ontkoppeling', box3Desc: 'Bodem is een levend ecosysteem. Zodra een monster wordt genomen, begint de microbiologische structuur af te breken.', box4Title: 'Statische Data vs. Dynamische Stroom', box4Desc: 'Labtests geven slechts een momentopname. Landbouw is een continu dynamisch proces.' },
  security: { watermark: 'BEVEILIGING', tag: 'Cyberschild', title: 'Onveranderlijke Data,', title2: 'Ontoegankelijke Hardware.', desc: 'Het NaT-ecosysteem is beschermd door AES-256-encryptie van militair niveau. Uw gegevens zijn <strong>end-to-end versleuteld</strong>.', card1Title: 'Match-Lock Protocol', card1Desc: 'Bij verbinding wordt het apparaat <strong>cryptografisch gekoppeld</strong> aan het gebruikersaccount en schakelt over naar onzichtbare modus.', card1Badge: 'Stealth-modus Actief', card2Title: 'Digitale Genetische Code', card2Desc: 'Elk apparaat wordt in de fabriek verzegeld met een <strong>uniek 30-cijferig</strong> serienummer.', card2Badge: '30-Cijferig Serienummer', card3Title: 'BLOB SQL — Onveranderlijke Records', card3Desc: 'Alle records worden opgeslagen in BLOB-formaat en gekoppeld met een <strong>cryptografische hashketen</strong>.', card3Badge: 'Achteraf Verifieerbaar' },
  vision: { tag: 'Doe Mee', title: 'Landbouw Transformeren naar een', title2: 'Mensloos, Verspillingsvrij Ecosysteem.', desc1: 'Bij NaT ontwikkelen we een datagestuurde, volledig autonome oplossing. Onze visie: landbouw bevrijden van externe afhankelijkheden.', desc2: 'Wij nodigen engelinvesteerders, strategische partners en innovatiepioniers uit om zich bij ons aan te sluiten.', cta: 'Neem Contact op met het Oprichtersteam' },
  footer: { ecosystem: 'Ecosysteem', company: 'Bedrijf', legal: 'Juridisch', home: 'Home', career: 'Carrière', contact: 'Contact', privacy: 'Privacybeleid', kvkk: 'Gegevensbescherming', terms: 'Gebruiksvoorwaarden', copyright: '© 2026 NaT — Natural Agriculture Technologies. Alle rechten voorbehouden.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Stuur ons een bericht!', infoTag: 'Contact', infoTitleHtml: 'Red de<br/>wereld<br/><span class="highlight-text"><b>samen</b>!</span>', infoDesc: 'Wij staan klaar voor al uw vragen over investering, samenwerking, carrière of onze producten.', emailLabel: 'E-mail', coFounder: 'Medeoprichter & Eigenaar', locationLabel: 'Locatie', location: 'Turkije', formTitle: 'Stuur Uw Bericht', nameField: 'Volledige Naam', emailField: 'E-mailadres', nameError: 'Dit veld is verplicht.', emailError: 'Voer een geldig e-mailadres in.', orgToggleTitle: 'Ik schrijf namens een bedrijf of organisatie', orgToggleDesc: 'Deel aanvullende informatie voor zakelijke berichten.', orgNameField: 'Bedrijf / Organisatie', orgRoleField: 'Titel / Functie', subjectLabel: 'Onderwerp', subjectInvest: 'Investering & Financiën', subjectPartner: 'Strategisch Partnerschap', subjectProduct: 'Product & Technologie', subjectCareer: 'Carrière & Team', subjectMedia: 'Media & Pers', subjectOther: 'Overig', subjectError: 'Selecteer een onderwerp.', messageField: 'Uw Bericht', messageError: 'Het berichtveld is verplicht.', submitBtn: 'Verzenden', submitting: 'Verzenden…', privacyNote: 'Uw informatie is veilig en wordt niet gedeeld met derden.', successMsg: 'Uw bericht is succesvol verzonden!', errorMsg: 'Er is een fout opgetreden. Probeer het later opnieuw.', watermark: 'CONTACT' },
};
