import type { TranslationSet } from './types';
export const pt: TranslationSet = {
  nav: { home: 'Início', problem: 'Problema', hardware: 'Hardware', intelligence: 'Inteligência', operation: 'Operação', security: 'Segurança', join: 'Junte-se!', mobileToggle: 'Menu móvel', mobileNav: 'Navegação móvel', mainNav: 'Navegação principal' },
  hero: { subtitle: 'Contra a crise global, estamos construindo um ecossistema agrícola totalmente autônomo baseado em RAG.', exploreBtn: 'Descubra Nossa Visão', pitchBtn: 'Baixar Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Crise Global', title: 'Conhecemos o Problema. Estamos Construindo a Solução.', desc: 'Para alimentar <strong>10 bilhões de pessoas até 2050</strong>, precisamos aumentar a produção em 60%.', card1Title: 'Catástrofe Silenciosa', card1Desc: '<strong>70%</strong> da água doce é usada na agricultura.', card2Title: 'Vulnerabilidade Climática', card2Desc: 'A agricultura convencional está à mercê da natureza.', card3Title: 'Isolamento de Dados', card3Desc: 'Os dados agrícolas permanecem locais e isolados.' },
  coreVision: { tag: 'Design do Ecossistema', title: 'Simulação Perfeita de Microclima\npara Cada Planta.', desc: 'Na NaT, criamos um sistema que <strong>muda o ambiente</strong>.', feat1Title: 'Adaptação Dinâmica', feat1Desc: 'O sistema lê as necessidades metabólicas imediatas das plantas.', feat2Title: 'Rede de Suplementação Precisa', feat2Desc: 'Fornece <strong>nutrientes, água, calor e fertilizante</strong> com precisão.', feat3Title: 'Motor de Decisão Autônomo', feat3Desc: '<strong>Ativa automaticamente</strong> micro-intervenções.' },
  hardware: { watermark: 'HARDWARE', tag: 'P&D Hardware', title: 'Inteligência Integrada: sensSeries', desc: 'Projetando a família de hardware do ecossistema NaT.', sensTreeDesc: 'Dispositivo IoT robusto montado no tronco.', sensSoilDesc: 'Sensor subterrâneo para penetração no solo.', sensPlantDesc: 'Dispositivo tipo clipe para mudas.' },
  rag: { watermark: 'INTELIGÊNCIA', tag: 'IA Baseada em RAG', title: 'Experiência Global, Ação Local.', desc: 'Arquitetura RAG combinando LLMs com bancos de dados agrícolas.', pred1Title: 'Previsão Proativa', pred1Desc: 'NaT prevê: "esta doença tem risco de 84% em 3 dias."', pred2Title: 'Aprendizado Federado Coletivo', pred2Desc: 'Cada dispositivo NaT treina o modelo central preservando a privacidade.' },
  operation: { watermark: 'OPERAÇÃO', tag: 'Visão Operacional', title: 'Transição Autônoma do Diagnóstico ao Tratamento', desc: 'Nosso objetivo: transformar dados em ação física autônoma.', card1Title: 'Integração API', card1Desc: 'A IA envia comandos de <strong>intervenção direcionada</strong> a drones.', card2Title: 'Rendimento Máximo', card2Desc: 'Reduzindo o uso de químicos <strong>em até 85%</strong>.' },
  lab: { title: 'Em 4 Passos', subtitle: 'Superamos os testes de laboratório.', box1Title: 'Perda de Tempo', box1Desc: 'Coleta e resultados levam dias.', box2Title: 'Viés de Amostragem', box2Desc: 'Punhados de terra representam um campo inteiro.', box3Title: 'Desconexão do Ecossistema', box3Desc: 'Ao extrair uma amostra, a estrutura se degrada.', box4Title: 'Dados Estáticos vs. Dinâmico', box4Desc: 'Testes fornecem apenas um instantâneo.' },
  security: { watermark: 'SEGURANÇA', tag: 'Escudo Cibernético', title: 'Dados Imutáveis,', title2: 'Hardware Inacessível.', desc: 'Seus dados são <strong>criptografados de ponta a ponta</strong>.', card1Title: 'Protocolo Match-Lock', card1Desc: 'Dispositivo <strong>pareado criptograficamente</strong>.', card1Badge: 'Modo Invisível Ativo', card2Title: 'Código Genético Digital', card2Desc: 'Série <strong>única de 30 dígitos</strong>.', card2Badge: 'Série de 30 Dígitos', card3Title: 'BLOB SQL — Registros Imutáveis', card3Desc: 'Vinculados por <strong>cadeia hash criptográfica</strong>.', card3Badge: 'Verificável Retroativamente' },
  vision: { tag: 'Junte-se', title: 'Transformando a Agricultura em um', title2: 'Ecossistema Sem Humanos e Sem Desperdício.', desc1: 'Na NaT, desenvolvemos uma solução autônoma.', desc2: 'Convidamos investidores e parceiros a se juntarem.', cta: 'Contatar a Equipe Fundadora' },
  footer: { ecosystem: 'Ecossistema', company: 'Empresa', legal: 'Jurídico', home: 'Início', career: 'Carreira', contact: 'Contato', privacy: 'Política de Privacidade', kvkk: 'Proteção de Dados', terms: 'Termos de Uso', copyright: '© 2026 NaT — Natural Agriculture Technologies. Todos os direitos reservados.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Envie-nos uma mensagem!', infoTag: 'Contato', infoTitleHtml: 'Vamos salvar<br/>o mundo<br/><span class="highlight-text"><b>juntos</b>!</span>', infoDesc: 'Estamos aqui para suas perguntas.', emailLabel: 'E-mail', coFounder: 'Co-Fundador e Proprietário', locationLabel: 'Localização', location: 'Turquia', formTitle: 'Envie Sua Mensagem', nameField: 'Nome Completo', emailField: 'E-mail', nameError: 'Campo obrigatório.', emailError: 'Insira um e-mail válido.', orgToggleTitle: 'Escrevo em nome de uma empresa', orgToggleDesc: 'Compartilhe detalhes adicionais.', orgNameField: 'Nome da Empresa', orgRoleField: 'Cargo / Posição', subjectLabel: 'Assunto', subjectInvest: 'Investimento e Finanças', subjectPartner: 'Parceria Estratégica', subjectProduct: 'Produto e Tecnologia', subjectCareer: 'Carreira e Equipe', subjectMedia: 'Mídia e Imprensa', subjectOther: 'Outro', subjectError: 'Selecione um assunto.', messageField: 'Sua Mensagem', messageError: 'Campo obrigatório.', submitBtn: 'Enviar', submitting: 'Enviando…', privacyNote: 'Informações seguras.', successMsg: 'Mensagem enviada!', errorMsg: 'Erro. Tente novamente.', watermark: 'CONTATO' },
};
