import type { TranslationSet } from './types';
export const pt: TranslationSet = {
  nav: { home: 'Início', problem: 'Problema', hardware: 'Hardware', intelligence: 'Inteligência', operation: 'Operação', security: 'Segurança', join: 'Junte-se!', mobileToggle: 'Menu móvel', mobileNav: 'Navegação móvel', mainNav: 'Navegação principal' },
  hero: { subtitle: 'Contra a crise global da água e dos alimentos, estamos construindo um ecossistema agrícola totalmente autônomo baseado em RAG, capaz de simular seu próprio microclima para cada planta.', exploreBtn: 'Descubra Nossa Visão', pitchBtn: 'Baixar Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Crise Global', title: 'Conhecemos o Problema. Estamos Construindo a Solução.', desc: 'A agricultura global está à beira do colapso. Para alimentar <strong>10 bilhões de pessoas até 2050</strong>, precisamos aumentar a produção em 60% — impossível com métodos atuais.', card1Title: 'Catástrofe Silenciosa: Desperdício de Água', card1Desc: '<strong>70%</strong> da água doce mundial é usada na agricultura, e metade se perde por evaporação ou irrigação incorreta.', card2Title: 'Vulnerabilidade Climática', card2Desc: 'A agricultura convencional está à mercê da natureza. Uma geada inesperada pode destruir o trabalho de um ano em dias.', card3Title: 'Isolamento de Dados', card3Desc: 'Os dados agrícolas permanecem locais e isolados. Agricultores repetem os mesmos erros sem mecanismo de aprendizado coletivo.' },
  coreVision: { tag: 'Design do Ecossistema', title: 'Simulação Perfeita de Microclima\npara Cada Planta, em Qualquer Lugar.', desc: 'Na NaT, nosso objetivo é criar um sistema reativo e autônomo que não apenas lê dados — <strong>muda o ambiente</strong>.', feat1Title: 'Adaptação Dinâmica', feat1Desc: 'Independentemente de onde esteja seu campo, o sistema lê as necessidades metabólicas imediatas das plantas.', feat2Title: 'Rede de Suplementação Precisa', feat2Desc: 'Fornece <strong>nutrientes, água, calor e fertilizante</strong> com precisão de miligramas, apenas quando necessário.', feat3Title: 'Motor de Decisão Autônomo', feat3Desc: 'Antes da planta sofrer estresse, <strong>ativa automaticamente</strong> micro-intervenções para neutralizar efeitos climáticos adversos.' },
  hardware: { watermark: 'HARDWARE', tag: 'P&D Hardware', title: 'Inteligência Integrada ao Campo: sensSeries', desc: 'Estamos projetando a família de hardware que servirá como terminações nervosas do ecossistema NaT.', sensTreeDesc: 'Um dispositivo IoT robusto montado diretamente no tronco para monitorar processos biológicos das árvores.', sensSoilDesc: 'Um sensor subterrâneo com design afiado para penetração fácil no solo, medindo NPK, pH e umidade.', sensPlantDesc: 'Um dispositivo de rastreamento tipo clipe para mudas, analisando mudanças bioquímicas para detectar doenças antes dos sintomas.' },
  rag: { watermark: 'INTELIGÊNCIA', tag: 'IA Baseada em RAG', title: 'Experiência Global, Ação Local.', desc: 'Nossa equipe está construindo uma arquitetura RAG que combina o poder dos LLMs com bancos de dados agrícolas.', pred1Title: 'Previsão Proativa', pred1Desc: 'NaT está sendo treinado para processar dados e prever: "esta doença tem risco de 84% em 3 dias."', pred2Title: 'Aprendizado Federado Coletivo', pred2Desc: 'Cada dispositivo NaT treina o modelo central preservando a privacidade. Uma estratégia da Argentina é aplicada em Konya em segundos.' },
  operation: { watermark: 'OPERAÇÃO', tag: 'Visão Operacional', title: 'Transição Autônoma do Diagnóstico ao Tratamento', desc: 'Coletar dados é apenas metade do trabalho. Nosso objetivo real: transformar dados em ação física autônoma.', card1Title: 'Integração API e Intervenção Direcionada', card1Desc: 'Quando nossa IA decide, envia comandos de <strong>intervenção direcionada</strong> diretamente a drones ou sistemas autônomos.', card2Title: 'Rendimento Máximo, Química Mínima', card2Desc: 'Tratamos apenas os metros quadrados específicos, reduzindo o uso de químicos <strong>em até 85%</strong>.' },
  lab: { title: 'Em 4 Passos', subtitle: 'Superamos os testes de laboratório.', box1Title: 'Perda de Tempo e Resposta Atrasada', box1Desc: 'Testes de laboratório criam enorme perda de tempo. Coleta de amostras e resultados levam dias.', box2Title: 'Viés de Amostragem e Representação', box2Desc: 'Apenas punhados de terra representam um campo inteiro. Mas a estrutura do solo nunca é homogênea.', box3Title: 'Desconexão do Ecossistema', box3Desc: 'O solo é um ecossistema vivo. Ao extrair uma amostra, sua estrutura microbiológica começa a se degradar.', box4Title: 'Dados Estáticos vs. Fluxo Dinâmico', box4Desc: 'Testes de laboratório fornecem apenas um instantâneo. A agricultura é um processo dinâmico constante.' },
  security: { watermark: 'SEGURANÇA', tag: 'Escudo Cibernético', title: 'Dados Imutáveis,', title2: 'Hardware Inacessível.', desc: 'O ecossistema NaT é protegido por criptografia AES-256 de nível militar. Seus dados são <strong>criptografados de ponta a ponta</strong>.', card1Title: 'Protocolo Match-Lock', card1Desc: 'Ao conectar, o dispositivo é <strong>pareado criptograficamente</strong> com a conta do usuário e entra em modo invisível.', card1Badge: 'Modo Invisível Ativo', card2Title: 'Código Genético Digital', card2Desc: 'Cada dispositivo é selado na fábrica com um número de série <strong>único de 30 dígitos</strong>.', card2Badge: 'Número de Série de 30 Dígitos', card3Title: 'BLOB SQL — Registros Imutáveis', card3Desc: 'Todos os registros são armazenados em formato BLOB e vinculados por uma <strong>cadeia hash criptográfica</strong>.', card3Badge: 'Verificável Retroativamente' },
  vision: { tag: 'Junte-se', title: 'Transformando a Agricultura em um', title2: 'Ecossistema Sem Humanos e Sem Desperdício.', desc1: 'Na NaT, desenvolvemos uma solução autônoma e orientada por dados. Nossa visão: libertar a agricultura de dependências externas.', desc2: 'Convidamos investidores anjo, parceiros estratégicos e pioneiros da inovação para se juntarem a nós.', cta: 'Contatar a Equipe Fundadora' },
  footer: { ecosystem: 'Ecossistema', company: 'Empresa', legal: 'Jurídico', home: 'Início', career: 'Carreira', contact: 'Contato', privacy: 'Política de Privacidade', kvkk: 'Proteção de Dados', terms: 'Termos de Uso', copyright: '© 2026 NaT — Natural Agriculture Technologies. Todos os direitos reservados.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Envie-nos uma mensagem!', infoTag: 'Contato', infoTitleHtml: 'Vamos salvar<br/>o mundo<br/><span class="highlight-text"><b>juntos</b>!</span>', infoDesc: 'Estamos aqui para todas as suas perguntas sobre investimento, colaboração, carreira ou nossos produtos.', emailLabel: 'E-mail', coFounder: 'Co-Fundador e Proprietário', locationLabel: 'Localização', location: 'Turquia', formTitle: 'Envie Sua Mensagem', nameField: 'Nome Completo', emailField: 'Endereço de E-mail', nameError: 'Este campo é obrigatório.', emailError: 'Insira um e-mail válido.', orgToggleTitle: 'Escrevo em nome de uma empresa ou organização', orgToggleDesc: 'Compartilhe detalhes adicionais para mensagens corporativas.', orgNameField: 'Nome da Empresa / Organização', orgRoleField: 'Cargo / Posição', subjectLabel: 'Assunto', subjectInvest: 'Investimento e Finanças', subjectPartner: 'Parceria Estratégica', subjectProduct: 'Produto e Tecnologia', subjectCareer: 'Carreira e Equipe', subjectMedia: 'Mídia e Imprensa', subjectOther: 'Outro', subjectError: 'Selecione um assunto.', messageField: 'Sua Mensagem', messageError: 'O campo de mensagem é obrigatório.', submitBtn: 'Enviar', submitting: 'Enviando…', privacyNote: 'Suas informações estão seguras e não serão compartilhadas com terceiros.', successMsg: 'Sua mensagem foi enviada com sucesso!', errorMsg: 'Ocorreu um erro. Tente novamente mais tarde.', watermark: 'CONTATO' },
};
