import type { TranslationSet } from './types';
export const sw: TranslationSet = {
  nav: { home: 'Nyumbani', problem: 'Tatizo', hardware: 'Vifaa', intelligence: 'Akili', operation: 'Operesheni', security: 'Usalama', join: 'Jiunge Nasi!', mobileToggle: 'Menyu ya simu', mobileNav: 'Urambazaji wa simu', mainNav: 'Urambazaji mkuu' },
  hero: { subtitle: 'Dhidi ya janga la maji na chakula duniani, tunajenga mfumo kamili wa kilimo unaojiendesha kwa RAG, unaoweza kuiga hali ya hewa ndogo kwa kila mmea.', exploreBtn: 'Gundua Maono Yetu', pitchBtn: 'Pakua Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Janga la Dunia', title: 'Tunajua Tatizo. Tunajenga Suluhisho.', desc: 'Kilimo cha dunia kinakaribia kuanguka. Ili kulisha <strong>watu bilioni 10 ifikapo 2050</strong>, lazima tuongeze uzalishaji kwa 60% — haiwezekani kwa njia za sasa.', card1Title: 'Janga Kimya: Upotevu wa Maji', card1Desc: '<strong>70%</strong> ya maji safi duniani hutumika kilimoni, na nusu hupotea kwa mvuke au umwagiliaji mbaya.', card2Title: 'Udhaifu wa Hali ya Hewa', card2Desc: 'Kilimo cha jadi kiko chini ya huruma ya asili. Baridi isiyotarajiwa inaweza kuharibu kazi ya mwaka mzima katika siku.', card3Title: 'Kutengwa kwa Data', card3Desc: 'Data za kilimo zinabaki za ndani na kutengwa. Wakulima wanarudia makosa yale yale bila utaratibu wa kujifunza pamoja.' },
  coreVision: { tag: 'Muundo wa Mfumo', title: 'Uigaji Kamili wa Hali ya Hewa Ndogo\nkwa Kila Mmea, Kila Mahali.', desc: 'Katika NaT, lengo letu ni kuunda mfumo wa kujiendesha ambao hausomi data tu — <strong>unabadilisha mazingira</strong>.', feat1Title: 'Kubadilika kwa Nguvu', feat1Desc: 'Bila kujali shamba lako liko wapi, mfumo unasoma mahitaji ya haraka ya mimea.', feat2Title: 'Mtandao wa Virutubisho Sahihi', feat2Desc: 'Unawasilisha <strong>virutubisho, maji, joto na mbolea</strong> kwa usahihi wa miligramu, tu inapohitajika.', feat3Title: 'Injini ya Maamuzi ya Kujiendesha', feat3Desc: 'Kabla mmea haujapata msongo, <strong>inazindua kiotomatiki</strong> hatua ndogo za kupunguza athari za hali ya hewa.' },
  hardware: { watermark: 'VIFAA', tag: 'Utafiti wa Vifaa', title: 'Akili Iliyopandikizwa Shambani: sensSeries', desc: 'Tunaunda familia ya vifaa ambayo itakuwa ncha za mishipa ya mfumo wa NaT.', sensTreeDesc: 'Kifaa cha IoT kinachowekwa moja kwa moja kwenye shina kufuatilia michakato ya kibiolojia ya miti.', sensSoilDesc: 'Sensori ya chini ya ardhi yenye muundo mkali wa kupenya udongo kwa urahisi, kipimo cha NPK, pH na unyevu.', sensPlantDesc: 'Kifaa cha kufuatilia kwa klipu kwa miche, kinachochambua mabadiliko ya kibayokemikali kugundua magonjwa kabla ya dalili.' },
  rag: { watermark: 'AKILI', tag: 'AI Inayotegemea RAG', title: 'Uzoefu wa Kimataifa, Hatua ya Ndani.', desc: 'Timu yetu inajenga usanifu wa RAG unaochanganya nguvu za LLM na hifadhidata za kilimo.', pred1Title: 'Utabiri wa Mapema', pred1Desc: 'NaT inafundishwa kusindika data na kutabiri: "ugonjwa huu una hatari ya 84% katika siku 3."', pred2Title: 'Kujifunza kwa Pamoja', pred2Desc: 'Kila kifaa cha NaT kinafundisha modeli kuu huku kikilinda faragha. Mkakati kutoka Argentina unatumika Konya katika sekunde.' },
  operation: { watermark: 'OPERESHENI', tag: 'Maono ya Uendeshaji', title: 'Mpito wa Kujiendesha kutoka Uchunguzi hadi Matibabu', desc: 'Kukusanya data ni nusu tu ya kazi. Lengo letu halisi: kubadilisha data kuwa hatua ya kimwili ya kujiendesha.', card1Title: 'Muunganisho wa API na Uingiliaji Uliolengwa', card1Desc: 'AI yetu inapofanya uamuzi, inatuma amri za <strong>uingiliaji uliolengwa</strong> moja kwa moja kwa ndege zisizokuwa na rubani.', card2Title: 'Mavuno ya Juu, Kemikali Kidogo', card2Desc: 'Tunatibu mita za mraba maalum tu, kupunguza matumizi ya kemikali <strong>hadi 85%</strong>.' },
  lab: { title: 'Katika Hatua 4', subtitle: 'Tunazidi majaribio ya maabara.', box1Title: 'Upotevu wa Muda na Jibu la Kuchelewa', box1Desc: 'Majaribio ya maabara yanasababisha upotevu mkubwa wa muda. Sampuli na matokeo huchukua siku.', box2Title: 'Upendeleo wa Sampuli na Uwakilishi', box2Desc: 'Kiganja cha udongo kinawakilisha shamba zima. Lakini muundo wa udongo si homogeneous kamwe.', box3Title: 'Kukatika na Mfumo wa Ikolojia', box3Desc: 'Udongo ni mfumo hai. Mara sampuli inapotolewa, muundo wake wa kibayolojia unaanza kuharibika.', box4Title: 'Data Tuli vs. Mtiririko wa Nguvu', box4Desc: 'Majaribio ya maabara yanatoa picha tu. Kilimo ni mchakato wa nguvu unaoendelea.' },
  security: { watermark: 'USALAMA', tag: 'Ngao ya Mtandao', title: 'Data Isiyobadilika,', title2: 'Vifaa Visivyofikika.', desc: 'Mfumo wa NaT unalindwa na usimbaji AES-256 wa kiwango cha kijeshi. Data yako <strong>imesimbwa mwisho hadi mwisho</strong>.', card1Title: 'Itifaki ya Match-Lock', card1Desc: 'Kikiunganishwa, kifaa <strong>kinaunganishwa kwa usimbaji</strong> na akaunti ya mtumiaji na kuingia hali isiyoonekana.', card1Badge: 'Hali Isiyoonekana Hai', card2Title: 'Msimbo wa Kijenetiki wa Kidigitali', card2Desc: 'Kila kifaa kimefungwa kiwandani na nambari ya serial <strong>ya kipekee ya tarakimu 30</strong>.', card2Badge: 'Nambari ya Serial ya Tarakimu 30', card3Title: 'BLOB SQL — Rekodi Zisizobadilika', card3Desc: 'Rekodi zote zimehifadhiwa katika muundo wa BLOB na kuunganishwa na <strong>mnyororo wa hash wa usimbaji</strong>.', card3Badge: 'Inaweza Kuthibitishwa Nyuma' },
  vision: { tag: 'Jiunge Nasi', title: 'Kubadilisha Kilimo kuwa', title2: 'Mfumo Usio na Binadamu, Usio na Taka.', desc1: 'Katika NaT, tunaendeleza suluhisho la kujiendesha linalotegemea data. Maono yetu: kukomboa kilimo kutoka utegemezi wa nje.', desc2: 'Tunawaalika wawekezaji, washirika wa kimkakati, na wabunifu wa ubunifu kujiunga nasi.', cta: 'Wasiliana na Timu ya Waanzilishi' },
  footer: { ecosystem: 'Mfumo', company: 'Kampuni', legal: 'Kisheria', home: 'Nyumbani', career: 'Kazi', contact: 'Mawasiliano', privacy: 'Sera ya Faragha', kvkk: 'Ulinzi wa Data', terms: 'Masharti ya Matumizi', copyright: '© 2026 NaT — Natural Agriculture Technologies. Haki zote zimehifadhiwa.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Tutumie ujumbe!', infoTag: 'Mawasiliano', infoTitleHtml: 'Tuokoe<br/>ulimwengu<br/><span class="highlight-text"><b>pamoja</b>!</span>', infoDesc: 'Tuko hapa kwa maswali yako yote kuhusu uwekezaji, ushirikiano, kazi au bidhaa zetu.', emailLabel: 'Barua pepe', coFounder: 'Mwanzilishi Mwenza na Mmiliki', locationLabel: 'Mahali', location: 'Uturuki', formTitle: 'Tuma Ujumbe Wako', nameField: 'Jina Kamili', emailField: 'Anwani ya Barua Pepe', nameError: 'Sehemu hii inahitajika.', emailError: 'Ingiza barua pepe halali.', orgToggleTitle: 'Ninaandika kwa niaba ya kampuni au shirika', orgToggleDesc: 'Shiriki maelezo ya ziada kwa ujumbe wa kampuni.', orgNameField: 'Jina la Kampuni / Shirika', orgRoleField: 'Cheo / Nafasi', subjectLabel: 'Mada', subjectInvest: 'Uwekezaji na Fedha', subjectPartner: 'Ushirikiano wa Kimkakati', subjectProduct: 'Bidhaa na Teknolojia', subjectCareer: 'Kazi na Timu', subjectMedia: 'Vyombo vya Habari', subjectOther: 'Nyingine', subjectError: 'Chagua mada.', messageField: 'Ujumbe Wako', messageError: 'Sehemu ya ujumbe inahitajika.', submitBtn: 'Tuma', submitting: 'Inatuma…', privacyNote: 'Taarifa zako ziko salama na hazitashirikiwa na wahusika wa tatu.', successMsg: 'Ujumbe wako umetumwa kwa mafanikio!', errorMsg: 'Hitilafu imetokea. Jaribu tena baadaye.', watermark: 'MAWASILIANO' },
};
