import type { TranslationSet } from './types';
export const sw: TranslationSet = {
  nav: { home: 'Nyumbani', problem: 'Tatizo', hardware: 'Vifaa', intelligence: 'Akili', operation: 'Operesheni', security: 'Usalama', join: 'Jiunge Nasi!', mobileToggle: 'Menyu ya simu', mobileNav: 'Urambazaji wa simu', mainNav: 'Urambazaji mkuu' },
  hero: { subtitle: 'Dhidi ya janga la maji na chakula duniani, tunajenga mfumo kamili wa kilimo unaojiendesha kwa RAG.', exploreBtn: 'Gundua Maono Yetu', pitchBtn: 'Pakua Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Janga la Dunia', title: 'Tunajua Tatizo. Tunajenga Suluhisho.', desc: 'Ili kulisha <strong>watu bilioni 10 ifikapo 2050</strong>, lazima tuongeze uzalishaji kwa 60%.', card1Title: 'Janga Kimya: Upotevu wa Maji', card1Desc: '<strong>70%</strong> ya maji safi hutumika kilimoni.', card2Title: 'Udhaifu wa Hali ya Hewa', card2Desc: 'Kilimo cha jadi kiko chini ya huruma ya asili.', card3Title: 'Kutengwa kwa Data', card3Desc: 'Data za kilimo zinabaki za ndani na kutengwa.' },
  coreVision: { tag: 'Muundo wa Mfumo', title: 'Uigaji Kamili wa Hali ya Hewa Ndogo\nkwa Kila Mmea.', desc: 'Mfumo unaobadilisha <strong>mazingira</strong>.', feat1Title: 'Kubadilika kwa Nguvu', feat1Desc: 'Mfumo unasoma mahitaji ya haraka ya mimea.', feat2Title: 'Mtandao wa Virutubisho', feat2Desc: 'Unawasilisha <strong>virutubisho, maji, joto na mbolea</strong> kwa usahihi.', feat3Title: 'Injini ya Maamuzi', feat3Desc: '<strong>Inazindua kiotomatiki</strong> hatua ndogo.' },
  hardware: { watermark: 'VIFAA', tag: 'Utafiti wa Vifaa', title: 'Akili Shambani: sensSeries', desc: 'Tunaunda familia ya vifaa ya mfumo wa NaT.', sensTreeDesc: 'Kifaa cha IoT kwenye shina.', sensSoilDesc: 'Sensori ya chini ya ardhi.', sensPlantDesc: 'Kifaa cha klipu kwa miche.' },
  rag: { watermark: 'AKILI', tag: 'AI ya RAG', title: 'Uzoefu wa Kimataifa, Hatua ya Ndani.', desc: 'Usanifu wa RAG unaochanganya LLM na hifadhidata za kilimo.', pred1Title: 'Utabiri wa Mapema', pred1Desc: 'NaT inatabiri: "ugonjwa huu una hatari ya 84% katika siku 3."', pred2Title: 'Kujifunza kwa Pamoja', pred2Desc: 'Kila kifaa kinafundisha modeli kuu huku kikilinda faragha.' },
  operation: { watermark: 'OPERESHENI', tag: 'Maono ya Uendeshaji', title: 'Mpito wa Kujiendesha kutoka Uchunguzi hadi Matibabu', desc: 'Lengo: kubadilisha data kuwa hatua ya kimwili.', card1Title: 'Muunganisho wa API', card1Desc: 'AI inatuma amri za <strong>uingiliaji uliolengwa</strong> kwa ndege zisizokuwa na rubani.', card2Title: 'Mavuno ya Juu', card2Desc: 'Kupunguza kemikali <strong>hadi 85%</strong>.' },
  lab: { title: 'Hatua 4', subtitle: 'Tunazidi majaribio ya maabara.', box1Title: 'Upotevu wa Muda', box1Desc: 'Sampuli na matokeo huchukua siku.', box2Title: 'Upendeleo wa Sampuli', box2Desc: 'Kiganja cha udongo kinawakilisha shamba zima.', box3Title: 'Kukatika na Mfumo', box3Desc: 'Mara sampuli inapotolewa, muundo unaharibika.', box4Title: 'Data Tuli vs. Mtiririko', box4Desc: 'Majaribio yanatoa picha tu.' },
  security: { watermark: 'USALAMA', tag: 'Ngao ya Mtandao', title: 'Data Isiyobadilika,', title2: 'Vifaa Visivyofikika.', desc: 'Data yako <strong>imesimbwa mwisho hadi mwisho</strong>.', card1Title: 'Itifaki ya Match-Lock', card1Desc: 'Kifaa <strong>kinaunganishwa kwa usimbaji</strong>.', card1Badge: 'Hali Isiyoonekana', card2Title: 'Msimbo wa Kijenetiki', card2Desc: 'Nambari ya serial <strong>ya kipekee ya tarakimu 30</strong>.', card2Badge: 'Tarakimu 30', card3Title: 'BLOB SQL — Rekodi Zisizobadilika', card3Desc: 'Kuunganishwa na <strong>mnyororo wa hash</strong>.', card3Badge: 'Inaweza Kuthibitishwa' },
  vision: { tag: 'Jiunge Nasi', title: 'Kubadilisha Kilimo kuwa', title2: 'Mfumo Usio na Binadamu, Usio na Taka.', desc1: 'Katika NaT, tunaendeleza suluhisho la kujiendesha.', desc2: 'Tunawaalika wawekezaji na washirika kujiunga.', cta: 'Wasiliana na Timu ya Waanzilishi' },
  footer: { ecosystem: 'Mfumo', company: 'Kampuni', legal: 'Kisheria', home: 'Nyumbani', career: 'Kazi', contact: 'Mawasiliano', privacy: 'Sera ya Faragha', kvkk: 'Ulinzi wa Data', terms: 'Masharti ya Matumizi', copyright: '© 2026 NaT — Natural Agriculture Technologies. Haki zote zimehifadhiwa.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Tutumie ujumbe!', infoTag: 'Mawasiliano', infoTitleHtml: 'Tuokoe<br/>ulimwengu<br/><span class="highlight-text"><b>pamoja</b>!</span>', infoDesc: 'Tuko hapa kwa maswali yako yote.', emailLabel: 'Barua pepe', coFounder: 'Mwanzilishi Mwenza', locationLabel: 'Mahali', location: 'Uturuki', formTitle: 'Tuma Ujumbe', nameField: 'Jina Kamili', emailField: 'Barua Pepe', nameError: 'Sehemu hii inahitajika.', emailError: 'Ingiza barua pepe halali.', orgToggleTitle: 'Ninaandika kwa niaba ya kampuni', orgToggleDesc: 'Shiriki maelezo ya ziada.', orgNameField: 'Jina la Kampuni', orgRoleField: 'Cheo', subjectLabel: 'Mada', subjectInvest: 'Uwekezaji na Fedha', subjectPartner: 'Ushirikiano', subjectProduct: 'Bidhaa na Teknolojia', subjectCareer: 'Kazi na Timu', subjectMedia: 'Vyombo vya Habari', subjectOther: 'Nyingine', subjectError: 'Chagua mada.', messageField: 'Ujumbe Wako', messageError: 'Sehemu inahitajika.', submitBtn: 'Tuma', submitting: 'Inatuma…', privacyNote: 'Taarifa zako ziko salama.', successMsg: 'Ujumbe umetumwa!', errorMsg: 'Hitilafu. Jaribu tena.', watermark: 'MAWASILIANO' },
};
