import type { TranslationSet } from './types';
export const uk: TranslationSet = {
  nav: { home: 'Головна', problem: 'Проблема', hardware: 'Обладнання', intelligence: 'Інтелект', operation: 'Операція', security: 'Безпека', join: 'Приєднуйтесь!', mobileToggle: 'Мобільне меню', mobileNav: 'Мобільна навігація', mainNav: 'Основна навігація' },
  hero: { subtitle: 'Проти глобальної кризи ми будуємо повністю автономну сільськогосподарську екосистему на основі RAG.', exploreBtn: 'Дізнатися Нашу Візію', pitchBtn: 'Завантажити Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Глобальна Криза', title: 'Ми Знаємо Проблему. Ми Будуємо Рішення.', desc: 'Щоб нагодувати <strong>10 мільярдів людей до 2050</strong>, потрібно збільшити виробництво на 60%.', card1Title: 'Тиха Катастрофа', card1Desc: '<strong>70%</strong> прісної води використовується в сільському господарстві.', card2Title: 'Кліматична Вразливість', card2Desc: 'Традиційне землеробство залежить від природи.', card3Title: 'Ізоляція Даних', card3Desc: 'Дані залишаються локальними та ізольованими.' },
  coreVision: { tag: 'Дизайн Екосистеми', title: 'Ідеальна Симуляція Мікроклімату\nдля Кожної Рослини.', desc: 'Система, яка <strong>змінює середовище</strong>.', feat1Title: 'Динамічна Адаптація', feat1Desc: 'Система зчитує метаболічні потреби рослин.', feat2Title: 'Мережа Точного Доповнення', feat2Desc: 'Постачає <strong>поживні речовини, воду, тепло та добрива</strong> з точністю.', feat3Title: 'Автономний Механізм Рішень', feat3Desc: '<strong>Автоматично запускає</strong> мікро-втручання.' },
  hardware: { watermark: 'ОБЛАДНАННЯ', tag: 'НДДКР', title: 'Інтелект у Полі: sensSeries', desc: 'Проектуємо сімейство обладнання екосистеми NaT.', sensTreeDesc: 'IoT-пристрій на стовбурі.', sensSoilDesc: 'Підземний датчик для ґрунту.', sensPlantDesc: 'Кліпсовий пристрій для саджанців.' },
  rag: { watermark: 'ІНТЕЛЕКТ', tag: 'ШІ на Основі RAG', title: 'Глобальний Досвід, Локальна Дія.', desc: 'Архітектура RAG з LLM та сільськогосподарськими базами даних.', pred1Title: 'Проактивний Прогноз', pred1Desc: 'NaT прогнозує: «ризик хвороби 84% через 3 дні».', pred2Title: 'Колективне Федеративне Навчання', pred2Desc: 'Кожен пристрій навчає центральну модель, зберігаючи конфіденційність.' },
  operation: { watermark: 'ОПЕРАЦІЯ', tag: 'Операційна Візія', title: 'Автономний Перехід від Діагностики до Лікування', desc: 'Мета: перетворити дані на автономну фізичну дію.', card1Title: 'API-інтеграція', card1Desc: 'ШІ надсилає команди <strong>точкового втручання</strong> дронам.', card2Title: 'Максимум Врожаю', card2Desc: 'Скорочення хімікатів <strong>до 85%</strong>.' },
  lab: { title: 'За 4 Кроки', subtitle: 'Ми перевершуємо лабораторні тести.', box1Title: 'Втрата Часу', box1Desc: 'Відбір проб та результати займають дні.', box2Title: 'Помилка Вибірки', box2Desc: 'Жменя землі представляє ціле поле.', box3Title: 'Відрив від Екосистеми', box3Desc: 'При вилученні зразка структура руйнується.', box4Title: 'Статичні Дані vs. Динамічний Потік', box4Desc: 'Лабораторні тести — миттєвий знімок.' },
  security: { watermark: 'БЕЗПЕКА', tag: 'Кібер-Щит', title: 'Незмінні Дані,', title2: 'Недоступне Обладнання.', desc: 'Ваші дані <strong>зашифровані наскрізь</strong>.', card1Title: 'Протокол Match-Lock', card1Desc: 'Пристрій <strong>криптографічно сполучається</strong>.', card1Badge: 'Режим Невидимості', card2Title: 'Цифровий Генетичний Код', card2Desc: '<strong>Унікальний 30-значний</strong> серійний номер.', card2Badge: '30-Значний Номер', card3Title: 'BLOB SQL — Незмінні Записи', card3Desc: 'Пов\'язані <strong>криптографічним хеш-ланцюжком</strong>.', card3Badge: 'Ретроспективно Перевіряється' },
  vision: { tag: 'Приєднуйтесь', title: 'Перетворюємо Сільське Господарство на', title2: 'Безлюдну, Безвідходну Екосистему.', desc1: 'У NaT ми розробляємо автономне рішення на основі даних.', desc2: 'Ми запрошуємо інвесторів та партнерів приєднатися.', cta: 'Зв\'язатися з Командою Засновників' },
  footer: { ecosystem: 'Екосистема', company: 'Компанія', legal: 'Правова Інформація', home: 'Головна', career: 'Кар\'єра', contact: 'Контакт', privacy: 'Політика Конфіденційності', kvkk: 'Захист Даних', terms: 'Умови Використання', copyright: '© 2026 NaT — Natural Agriculture Technologies. Усі права захищені.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Надішліть нам повідомлення!', infoTag: 'Контакт', infoTitleHtml: 'Врятуємо<br/>світ<br/><span class="highlight-text"><b>разом</b>!</span>', infoDesc: 'Ми тут для всіх ваших питань.', emailLabel: 'E-mail', coFounder: 'Співзасновник та Власник', locationLabel: 'Місцезнаходження', location: 'Туреччина', formTitle: 'Надішліть Повідомлення', nameField: 'Повне Ім\'я', emailField: 'Адреса E-mail', nameError: 'Обов\'язкове поле.', emailError: 'Введіть дійсний e-mail.', orgToggleTitle: 'Пишу від імені компанії', orgToggleDesc: 'Поділіться деталями.', orgNameField: 'Назва Компанії', orgRoleField: 'Посада', subjectLabel: 'Тема', subjectInvest: 'Інвестиції та Фінанси', subjectPartner: 'Стратегічне Партнерство', subjectProduct: 'Продукт та Технології', subjectCareer: 'Кар\'єра та Команда', subjectMedia: 'ЗМІ та Преса', subjectOther: 'Інше', subjectError: 'Виберіть тему.', messageField: 'Ваше Повідомлення', messageError: 'Поле обов\'язкове.', submitBtn: 'Надіслати', submitting: 'Надсилання…', privacyNote: 'Ваша інформація в безпеці.', successMsg: 'Повідомлення надіслано!', errorMsg: 'Виникла помилка. Спробуйте пізніше.', watermark: 'КОНТАКТ' },
};
