import type { TranslationSet } from './types';
export const vi: TranslationSet = {
  nav: { home: 'Trang chủ', problem: 'Vấn đề', hardware: 'Phần cứng', intelligence: 'Trí tuệ', operation: 'Vận hành', security: 'Bảo mật', join: 'Tham gia!', mobileToggle: 'Menu di động', mobileNav: 'Điều hướng di động', mainNav: 'Điều hướng chính' },
  hero: { subtitle: 'Đối mặt với khủng hoảng nước và lương thực toàn cầu, chúng tôi đang xây dựng một hệ sinh thái nông nghiệp hoàn toàn tự chủ dựa trên RAG, có khả năng mô phỏng vi khí hậu riêng cho từng cây trồng.', exploreBtn: 'Khám phá tầm nhìn', pitchBtn: 'Tải Pitch Deck', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: 'Khủng hoảng toàn cầu', title: 'Chúng tôi biết vấn đề. Chúng tôi đang xây giải pháp.', desc: 'Nông nghiệp toàn cầu đang tiến đến sụp đổ. Để nuôi sống <strong>10 tỷ người vào năm 2050</strong>, sản lượng phải tăng 60% — điều không thể với phương pháp hiện tại.', card1Title: 'Thảm họa thầm lặng: Lãng phí nước', card1Desc: '<strong>70%</strong> nước ngọt thế giới được dùng trong nông nghiệp, một nửa trong số đó bị mất do bốc hơi hoặc tưới tiêu sai cách.', card2Title: 'Tính dễ tổn thương với khí hậu', card2Desc: 'Nông nghiệp truyền thống phụ thuộc hoàn toàn vào thiên nhiên. Một đợt sương giá bất ngờ có thể phá hủy công sức cả năm chỉ trong vài ngày.', card3Title: 'Cô lập dữ liệu', card3Desc: 'Dữ liệu nông nghiệp vẫn còn cục bộ và bị cô lập. Nông dân lặp lại những sai lầm như nhau mà không có cơ chế học tập tập thể.' },
  coreVision: { tag: 'Thiết kế hệ sinh thái', title: 'Cho mọi cây trồng, ở mọi nơi,\nMô phỏng vi khí hậu hoàn hảo.', desc: 'Mục tiêu của NaT là một hệ thống phản ứng và tự chủ không chỉ đọc dữ liệu mà còn <strong>thay đổi môi trường</strong>.', feat1Title: 'Thích nghi động', feat1Desc: 'Bất kể vị trí của cánh đồng, hệ thống đọc nhu cầu trao đổi chất tức thời của cây trồng.', feat2Title: 'Mạng bổ sung chính xác', feat2Desc: 'Cung cấp <strong>chất dinh dưỡng, nước, nhiệt và phân bón</strong> với độ chính xác miligam, chỉ khi cần thiết.', feat3Title: 'Động cơ quyết định tự chủ', feat3Desc: 'Trước khi cây trồng chịu stress, hệ thống <strong>tự động kích hoạt</strong> can thiệp vi mô để trung hòa tác động khí hậu.' },
  hardware: { watermark: 'PHẦN CỨNG', tag: 'R&D Phần cứng', title: 'Trí tuệ nhúng trong đồng ruộng: series sens', desc: 'Chúng tôi đang phát triển dòng phần cứng sẽ hoạt động như các đầu dây thần kinh của hệ sinh thái NaT.', sensTreeDesc: 'Thiết bị IoT chắc chắn gắn trực tiếp lên thân cây để theo dõi các quá trình sinh học của cây.', sensSoilDesc: 'Cảm biến dưới đất với thiết kế nhọn để dễ dàng xuyên đất, đo NPK, pH và độ ẩm.', sensPlantDesc: 'Thiết bị theo dõi dạng kẹp cho cây con, phân tích biến đổi sinh hóa để phát hiện bệnh trước khi có triệu chứng.' },
  rag: { watermark: 'TRÍ TUỆ', tag: 'AI dựa trên RAG', title: 'Kinh nghiệm toàn cầu, Hành động địa phương.', desc: 'Nhóm của chúng tôi đang xây dựng kiến trúc RAG kết hợp sức mạnh của LLM với cơ sở dữ liệu nông nghiệp.', pred1Title: 'Dự báo chủ động', pred1Desc: 'NaT được huấn luyện để xử lý dữ liệu thực địa và dự báo: "Bệnh này có nguy cơ 84% trong 3 ngày."', pred2Title: 'Học liên kết tập thể', pred2Desc: 'Mỗi thiết bị NaT huấn luyện mô hình trung tâm trong khi bảo vệ quyền riêng tư. Chiến lược từ Argentina được áp dụng ở Konya trong vài giây.' },
  operation: { watermark: 'VẬN HÀNH', tag: 'Tầm nhìn vận hành', title: 'Chuyển đổi tự chủ từ chẩn đoán sang điều trị', desc: 'Thu thập dữ liệu chỉ là một nửa công việc. Mục tiêu của chúng tôi: chuyển đổi dữ liệu thành hành động vật lý tự chủ.', card1Title: 'Tích hợp API và can thiệp có chủ đích', card1Desc: 'Khi AI của chúng tôi quyết định, nó gửi lệnh <strong>can thiệp có chủ đích</strong> trực tiếp đến drone hoặc hệ thống tự chủ.', card2Title: 'Năng suất tối đa, hóa chất tối thiểu', card2Desc: 'Chúng tôi chỉ điều trị những mét vuông cụ thể bị nhiễm bệnh — giảm sử dụng hóa chất <strong>lên đến 85%</strong>.' },
  lab: { title: 'Trong 4 bước', subtitle: 'Vượt qua xét nghiệm phòng thí nghiệm.', box1Title: 'Mất thời gian và phản ứng chậm trễ', box1Desc: 'Xét nghiệm phòng thí nghiệm gây ra tổn thất thời gian lớn. Lấy mẫu và kết quả mất nhiều ngày.', box2Title: 'Sai số lấy mẫu và tính đại diện', box2Desc: 'Chỉ một nắm đất đại diện cho cả cánh đồng. Nhưng cấu trúc đất không bao giờ đồng nhất.', box3Title: 'Tách biệt hệ sinh thái', box3Desc: 'Đất là một hệ sinh thái sống. Ngay khi lấy mẫu, quá trình phân hủy vi sinh bắt đầu.', box4Title: 'Dữ liệu tĩnh so với dòng chảy động', box4Desc: 'Xét nghiệm phòng thí nghiệm chỉ cung cấp ảnh chụp nhanh tại thời điểm. Nông nghiệp luôn là quá trình động.' },
  security: { watermark: 'BẢO MẬT', tag: 'Lá chắn mạng', title: 'Dữ liệu bất biến,', title2: 'Phần cứng không thể truy cập.', desc: 'Hệ sinh thái NaT được bảo vệ bằng mã hóa AES-256 cấp độ quân sự. Dữ liệu của bạn được <strong>mã hóa đầu cuối</strong>.', card1Title: 'Giao thức Match-Lock', card1Desc: 'Khi kết nối, thiết bị được <strong>ghép cặp bằng mật mã</strong> và chuyển sang chế độ tàng hình.', card1Badge: 'Chế độ tàng hình kích hoạt', card2Title: 'Mã gen kỹ thuật số', card2Desc: 'Mỗi thiết bị được niêm phong bằng số sê-ri <strong>30 chữ số duy nhất</strong>.', card2Badge: 'Số sê-ri 30 chữ số', card3Title: 'BLOB SQL — Hồ sơ bất biến', card3Desc: 'Tất cả hồ sơ được lưu ở định dạng BLOB và liên kết bằng <strong>chuỗi hash mật mã</strong>.', card3Badge: 'Có thể xác minh hồi tố' },
  vision: { tag: 'Tham gia', title: 'Chuyển đổi nông nghiệp thành', title2: 'Hệ sinh thái không người, không rác thải.', desc1: 'Tại NaT, chúng tôi đang phát triển giải pháp hoàn toàn tự chủ dựa trên dữ liệu cho cuộc khủng hoảng nông nghiệp toàn cầu. Tầm nhìn của chúng tôi: giải phóng nông nghiệp khỏi sự phụ thuộc.', desc2: 'Chúng tôi mời các nhà đầu tư thiên thần, đối tác chiến lược và những người tiên phong đổi mới cùng tham gia.', cta: 'Liên hệ nhóm sáng lập' },
  footer: { ecosystem: 'Hệ sinh thái', company: 'Công ty', legal: 'Pháp lý', home: 'Trang chủ', career: 'Nghề nghiệp', contact: 'Liên hệ', privacy: 'Chính sách bảo mật', kvkk: 'Bảo vệ dữ liệu', terms: 'Điều khoản sử dụng', copyright: '© 2026 NaT — Natural Agriculture Technologies. Bảo lưu mọi quyền.' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: 'Gửi tin nhắn cho chúng tôi!', infoTag: 'Liên hệ', infoTitleHtml: 'Hãy cùng<br/>cứu<br/><span class="highlight-text"><b>thế giới</b>!</span>', infoDesc: 'Chúng tôi sẵn sàng giải đáp mọi câu hỏi về đầu tư, hợp tác, nghề nghiệp hoặc sản phẩm của chúng tôi.', emailLabel: 'Email', coFounder: 'Đồng sáng lập & Chủ sở hữu', locationLabel: 'Địa điểm', location: 'Thổ Nhĩ Kỳ', formTitle: 'Gửi tin nhắn của bạn', nameField: 'Họ và tên', emailField: 'Địa chỉ email', nameError: 'Trường này là bắt buộc.', emailError: 'Vui lòng nhập email hợp lệ.', orgToggleTitle: 'Tôi viết thay mặt công ty hoặc tổ chức', orgToggleDesc: 'Chia sẻ thêm thông tin cho tin nhắn doanh nghiệp.', orgNameField: 'Công ty / Tổ chức', orgRoleField: 'Chức danh / Vị trí', subjectLabel: 'Chủ đề', subjectInvest: 'Đầu tư & Tài chính', subjectPartner: 'Đối tác chiến lược', subjectProduct: 'Sản phẩm & Công nghệ', subjectCareer: 'Nghề nghiệp & Nhóm', subjectMedia: 'Truyền thông & Báo chí', subjectOther: 'Khác', subjectError: 'Vui lòng chọn chủ đề.', messageField: 'Tin nhắn của bạn', messageError: 'Trường tin nhắn là bắt buộc.', submitBtn: 'Gửi', submitting: 'Đang gửi…', privacyNote: 'Thông tin của bạn được bảo mật và sẽ không được chia sẻ với bên thứ ba.', successMsg: 'Tin nhắn của bạn đã được gửi thành công!', errorMsg: 'Đã xảy ra lỗi. Vui lòng thử lại sau.', watermark: 'LIÊN HỆ' },
};
