import type { TranslationSet } from './types';
export const zh: TranslationSet = {
  nav: { home: '首页', problem: '问题', hardware: '硬件', intelligence: '智能', operation: '运营', security: '安全', join: '加入我们！', mobileToggle: '移动菜单', mobileNav: '移动导航', mainNav: '主导航' },
  hero: { subtitle: '面对全球水资源与粮食危机，我们正在构建一个完全自主的、基于RAG的农业生态系统，能够为每株植物模拟其独特的微气候。', exploreBtn: '探索我们的愿景', pitchBtn: '下载商业计划书', pdf: '/NaT_Executive_Vision_Paper_2026_ENG.pdf' },
  problem: { tag: '全球危机', title: '我们知道问题所在。我们正在构建解决方案。', desc: '全球农业正面临崩溃。要在2050年前养活<strong>100亿人口</strong>，必须将产量提高60%——这用现有方法根本无法实现。', card1Title: '无声的灾难：水资源浪费', card1Desc: '全球淡水的<strong>70%</strong>用于农业，其中一半因蒸发或不当灌溉而流失。', card2Title: '气候脆弱性', card2Desc: '传统农业完全依赖自然。一场意外霜冻可能在数天内摧毁一整年的劳动成果。', card3Title: '数据孤岛', card3Desc: '农业数据停留在本地且相互隔离。农民在没有集体学习机制的情况下反复犯同样的错误。' },
  coreVision: { tag: '生态系统设计', title: '为每株植物，在任何地方，\n实现完美微气候模拟。', desc: 'NaT的目标是构建一个不仅读取数据，更能<strong>改变环境</strong>的响应式自主系统。', feat1Title: '动态适应', feat1Desc: '无论农田位于何处，系统都能读取植物的即时代谢需求。', feat2Title: '精准补给网络', feat2Desc: '仅在必要时以毫克级精度提供<strong>营养素、水、热量和肥料</strong>。', feat3Title: '自主决策引擎', feat3Desc: '在植物感受到压力之前，<strong>自动触发</strong>微干预以中和气候影响。' },
  hardware: { watermark: '硬件', tag: '硬件研发', title: '嵌入农田的智能：sens系列', desc: '我们正在开发将作为NaT生态系统神经末梢的硬件系列。', sensTreeDesc: '直接安装在树干上的坚固IoT设备，用于监测树木的生物学过程。', sensSoilDesc: '具有尖锐设计的地下传感器，便于插入土壤，测量NPK、pH值和湿度。', sensPlantDesc: '夹式追踪设备，分析幼苗的生化变化，在症状出现前检测病害。' },
  rag: { watermark: '智能', tag: '基于RAG的AI', title: '全球经验，本地行动。', desc: '我们的团队正在构建结合LLM能力与农业数据库的RAG架构。', pred1Title: '主动预测', pred1Desc: 'NaT被训练处理田间数据并预测："这种病害3天后的风险为84%。"', pred2Title: '集体联邦学习', pred2Desc: '每台NaT设备在保护隐私的同时训练中央模型。来自阿根廷的策略在科尼亚数秒内得到应用。' },
  operation: { watermark: '运营', tag: '运营愿景', title: '从诊断到治疗的自主转变', desc: '数据收集只是工作的一半。我们的目标：将数据转化为自主的物理行动。', card1Title: 'API集成与精准干预', card1Desc: '当AI做出决策时，直接向无人机或自主系统发送<strong>精准干预</strong>指令。', card2Title: '最大产量，最少化学品', card2Desc: '只处理出现病害的特定区域，将化学品使用减少<strong>高达85%</strong>。' },
  lab: { title: '4个步骤', subtitle: '超越实验室检测。', box1Title: '时间损失与延迟反应', box1Desc: '实验室检测造成巨大时间损失。取样和获得结果需要数天时间。', box2Title: '采样误差与代表性', box2Desc: '一把土壤代表整片农田。但土壤结构从不均匀。', box3Title: '生态系统分离', box3Desc: '土壤是活的生态系统。样本被取出的那一刻，微生物分解便开始了。', box4Title: '静态数据与动态流程', box4Desc: '实验室检测只提供瞬间快照。农业是一个始终动态的过程。' },
  security: { watermark: '安全', tag: '网络盾牌', title: '不可篡改的数据，', title2: '无法访问的硬件。', desc: 'NaT生态系统受军事级AES-256加密保护。您的数据<strong>端到端加密</strong>。', card1Title: '匹配锁定协议', card1Desc: '连接时，设备进行<strong>密码学配对</strong>并切换到隐身模式。', card1Badge: '隐身模式激活', card2Title: '数字基因代码', card2Desc: '每台设备以<strong>唯一30位</strong>序列号封印。', card2Badge: '30位序列号', card3Title: 'BLOB SQL — 不可变记录', card3Desc: '所有记录以BLOB格式存储，并通过<strong>密码学哈希链</strong>连接。', card3Badge: '可溯源验证' },
  vision: { tag: '加入我们', title: '将农业转变为', title2: '无人化、零废弃的生态系统。', desc1: '在NaT，我们正在为全球农业危机开发数据驱动的完全自主解决方案。我们的愿景：将农业从依赖中解放出来。', desc2: '我们邀请天使投资人、战略合作伙伴和创新先驱加入我们。', cta: '联系创始团队' },
  footer: { ecosystem: '生态系统', company: '公司', legal: '法律', home: '首页', career: '职业', contact: '联系我们', privacy: '隐私政策', kvkk: '数据保护', terms: '使用条款', copyright: '© 2026 NaT — Natural Agriculture Technologies. 保留所有权利。' },
  contact: { heroSub: 'NaT — Natural Agriculture Technologies', heroTitle: '给我们发消息！', infoTag: '联系方式', infoTitleHtml: '让我们<br/>一起拯救<br/><span class="highlight-text"><b>世界</b>！</span>', infoDesc: '我们在这里解答您关于投资、合作、职业或产品的所有问题。', emailLabel: '电子邮件', coFounder: '联合创始人 & 所有者', locationLabel: '位置', location: '土耳其', formTitle: '发送您的消息', nameField: '全名', emailField: '电子邮件地址', nameError: '此字段为必填项。', emailError: '请输入有效的电子邮件地址。', orgToggleTitle: '我代表公司或组织发送消息', orgToggleDesc: '请分享企业消息的额外详情。', orgNameField: '公司 / 组织', orgRoleField: '职称 / 职位', subjectLabel: '主题', subjectInvest: '投资 & 融资', subjectPartner: '战略合作', subjectProduct: '产品 & 技术', subjectCareer: '职业 & 团队', subjectMedia: '媒体 & 新闻', subjectOther: '其他', subjectError: '请选择主题。', messageField: '您的消息', messageError: '消息字段为必填项。', submitBtn: '发送', submitting: '发送中…', privacyNote: '您的信息安全保密，不会与第三方共享。', successMsg: '您的消息已成功发送！', errorMsg: '发生错误。请稍后重试。', watermark: '联系' },
};
